"""
3PL Company Curated Seed Data.

Hand-curated enrichment data for the Transport Topics Top 100 3PL companies.
Each entry uses the exact company_name from the database to ensure matching.

Sources: Company websites, SEC filings, industry publications, press releases.
Last updated: 2026-02.
"""

# Each entry must have "company_name" matching the DB exactly.
# All other fields are optional enrichment — nulls are fine and will be skipped
# by the null_preserving_upsert.

THREE_PL_SEED_DATA = [
    {
        "company_name": "C.H. Robinson Worldwide",
        "headquarters_city": "Eden Prairie",
        "headquarters_state": "MN",
        "website": "https://www.chrobinson.com",
        "employee_count": 14695,
        "facility_count": 270,
        "services": ["freight_brokerage", "managed_transportation", "truckload", "ltl", "intermodal", "ocean", "air"],
        "industries_served": ["retail", "food_beverage", "manufacturing", "automotive"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America", "Europe", "Asia Pacific", "South America"],
        "states_coverage": ["MN", "IL", "TX", "CA", "GA", "NJ", "OH", "WA", "FL", "PA"],
    },
    {
        "company_name": "GXO Logistics",
        "headquarters_city": "Greenwich",
        "headquarters_state": "CT",
        "website": "https://www.gxo.com",
        "employee_count": 44000,
        "facility_count": 974,
        "services": ["warehousing", "distribution", "fulfillment", "contract_logistics", "reverse_logistics"],
        "industries_served": ["retail", "ecommerce", "food_beverage", "technology", "consumer_packaged_goods"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Europe", "Asia Pacific"],
        "states_coverage": ["CT", "CA", "TX", "GA", "OH", "PA", "IL", "TN", "NC", "IN"],
    },
    {
        "company_name": "XPO",
        "headquarters_city": "Greenwich",
        "headquarters_state": "CT",
        "website": "https://www.xpo.com",
        "employee_count": 38000,
        "facility_count": 610,
        "services": ["ltl", "truckload", "last_mile", "freight_brokerage"],
        "industries_served": ["retail", "manufacturing", "industrial", "ecommerce"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Europe"],
        "states_coverage": ["CT", "CA", "TX", "OH", "GA", "IL", "PA", "NC", "IN", "MI"],
    },
    {
        "company_name": "J.B. Hunt Transport Services",
        "headquarters_city": "Lowell",
        "headquarters_state": "AR",
        "website": "https://www.jbhunt.com",
        "employee_count": 34000,
        "facility_count": 150,
        "services": ["intermodal", "dedicated_transportation", "truckload", "freight_brokerage", "final_mile"],
        "industries_served": ["retail", "manufacturing", "consumer_goods", "home_delivery"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["AR", "TX", "CA", "IL", "OH", "GA", "PA", "IN", "TN", "NC"],
    },
    {
        "company_name": "Ryder System",
        "headquarters_city": "Miami",
        "headquarters_state": "FL",
        "website": "https://www.ryder.com",
        "employee_count": 48000,
        "facility_count": 800,
        "services": ["dedicated_transportation", "warehousing", "fleet_management", "supply_chain_management", "last_mile"],
        "industries_served": ["automotive", "technology", "retail", "industrial", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Europe"],
        "states_coverage": ["FL", "TX", "CA", "GA", "OH", "IL", "PA", "MI", "IN", "NC"],
    },
    {
        "company_name": "Expeditors International",
        "headquarters_city": "Seattle",
        "headquarters_state": "WA",
        "website": "https://www.expeditors.com",
        "employee_count": 18000,
        "facility_count": 350,
        "services": ["freight_forwarding", "customs_brokerage", "ocean", "air", "warehousing", "distribution"],
        "industries_served": ["technology", "retail", "aerospace", "manufacturing", "automotive"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America", "Asia Pacific", "Europe", "Middle East", "South America"],
        "states_coverage": ["WA", "CA", "TX", "IL", "NY", "GA", "OH", "NJ", "FL", "PA"],
    },
    {
        "company_name": "DHL Supply Chain",
        "headquarters_city": "Westerville",
        "headquarters_state": "OH",
        "website": "https://www.dhl.com/us-en/home/our-divisions/supply-chain.html",
        "employee_count": 49000,
        "facility_count": 500,
        "services": ["warehousing", "distribution", "fulfillment", "contract_logistics", "managed_transportation"],
        "industries_served": ["retail", "automotive", "technology", "life_sciences", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Global"],
        "states_coverage": ["OH", "CA", "TX", "IL", "GA", "PA", "NJ", "IN", "TN", "FL"],
    },
    {
        "company_name": "FedEx Logistics",
        "headquarters_city": "Memphis",
        "headquarters_state": "TN",
        "website": "https://www.fedex.com/en-us/logistics.html",
        "employee_count": 20000,
        "facility_count": 130,
        "services": ["freight_forwarding", "customs_brokerage", "ocean", "air", "truckload", "ltl"],
        "industries_served": ["retail", "technology", "healthcare", "aerospace", "automotive"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["TN", "TX", "CA", "IL", "GA", "OH", "PA", "NJ", "FL", "IN"],
    },
    {
        "company_name": "UPS Supply Chain Solutions",
        "headquarters_city": "Atlanta",
        "headquarters_state": "GA",
        "website": "https://www.ups.com/us/en/supplychain.page",
        "employee_count": 22000,
        "facility_count": 1000,
        "services": ["warehousing", "distribution", "freight_forwarding", "customs_brokerage", "truckload"],
        "industries_served": ["retail", "healthcare", "technology", "automotive", "industrial"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["GA", "KY", "TX", "CA", "IL", "NJ", "OH", "PA", "FL", "IN"],
    },
    {
        "company_name": "Kuehne + Nagel",
        "headquarters_city": "Jersey City",
        "headquarters_state": "NJ",
        "website": "https://www.kuehne-nagel.com",
        "employee_count": 78000,
        "facility_count": 1300,
        "services": ["ocean", "air", "contract_logistics", "warehousing", "customs_brokerage", "freight_forwarding"],
        "industries_served": ["retail", "technology", "pharmaceutical", "automotive", "industrial"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["NJ", "CA", "TX", "IL", "GA", "OH", "PA", "FL", "NY", "IN"],
    },
    {
        "company_name": "DB Schenker",
        "headquarters_city": "Chesapeake",
        "headquarters_state": "VA",
        "website": "https://www.dbschenker.com",
        "employee_count": 76000,
        "facility_count": 1850,
        "services": ["ocean", "air", "contract_logistics", "warehousing", "truckload", "freight_forwarding"],
        "industries_served": ["automotive", "technology", "industrial", "retail", "aerospace"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["VA", "CA", "TX", "IL", "GA", "OH", "NJ", "PA", "FL", "MI"],
    },
    {
        "company_name": "Schneider National",
        "headquarters_city": "Green Bay",
        "headquarters_state": "WI",
        "website": "https://www.schneider.com",
        "employee_count": 16000,
        "facility_count": 180,
        "services": ["truckload", "intermodal", "dedicated_transportation", "freight_brokerage", "warehousing"],
        "industries_served": ["retail", "manufacturing", "consumer_goods", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["WI", "TX", "CA", "IL", "GA", "OH", "PA", "IN", "TN", "NC"],
    },
    {
        "company_name": "Penske Logistics",
        "headquarters_city": "Reading",
        "headquarters_state": "PA",
        "website": "https://www.penskelogistics.com",
        "employee_count": 38000,
        "facility_count": 400,
        "services": ["dedicated_transportation", "warehousing", "distribution", "fleet_management", "supply_chain_management"],
        "industries_served": ["automotive", "retail", "food_beverage", "manufacturing", "healthcare"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Europe", "Asia Pacific", "South America"],
        "states_coverage": ["PA", "TX", "CA", "OH", "IL", "GA", "IN", "MI", "NJ", "TN"],
    },
    {
        "company_name": "Nippon Express",
        "headquarters_city": "New York",
        "headquarters_state": "NY",
        "website": "https://www.nipponexpress.com",
        "employee_count": 72000,
        "facility_count": 730,
        "services": ["freight_forwarding", "ocean", "air", "warehousing", "contract_logistics"],
        "industries_served": ["automotive", "technology", "semiconductor", "aerospace", "pharmaceutical"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["NY", "CA", "TX", "IL", "GA", "NJ", "OH", "MI", "PA", "FL"],
    },
    {
        "company_name": "DSV",
        "headquarters_city": "Iselin",
        "headquarters_state": "NJ",
        "website": "https://www.dsv.com",
        "employee_count": 75000,
        "facility_count": 1600,
        "services": ["ocean", "air", "freight_forwarding", "contract_logistics", "warehousing", "customs_brokerage"],
        "industries_served": ["automotive", "technology", "retail", "industrial", "healthcare"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["NJ", "CA", "TX", "IL", "GA", "OH", "PA", "FL", "NY", "MI"],
    },
    {
        "company_name": "CEVA Logistics",
        "headquarters_city": "Houston",
        "headquarters_state": "TX",
        "website": "https://www.cevalogistics.com",
        "employee_count": 78000,
        "facility_count": 900,
        "services": ["freight_forwarding", "contract_logistics", "ocean", "air", "warehousing", "distribution"],
        "industries_served": ["automotive", "technology", "energy", "healthcare", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["TX", "CA", "IL", "GA", "OH", "NJ", "PA", "FL", "MI", "TN"],
    },
    {
        "company_name": "Werner Enterprises",
        "headquarters_city": "Omaha",
        "headquarters_state": "NE",
        "website": "https://www.werner.com",
        "employee_count": 13000,
        "facility_count": 30,
        "services": ["truckload", "dedicated_transportation", "intermodal", "freight_brokerage"],
        "industries_served": ["retail", "manufacturing", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["NE", "TX", "CA", "IL", "GA", "OH", "PA", "IN", "FL", "TN"],
    },
    {
        "company_name": "Landstar System",
        "headquarters_city": "Jacksonville",
        "headquarters_state": "FL",
        "website": "https://www.landstar.com",
        "employee_count": 1200,
        "facility_count": 40,
        "services": ["truckload", "ltl", "freight_brokerage", "heavy_haul", "flatbed"],
        "industries_served": ["manufacturing", "construction", "energy", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["FL", "TX", "CA", "IL", "GA", "OH", "PA", "IN", "NC", "TN"],
    },
    {
        "company_name": "Old Dominion Freight Line",
        "headquarters_city": "Thomasville",
        "headquarters_state": "NC",
        "website": "https://www.odfl.com",
        "employee_count": 24000,
        "facility_count": 256,
        "services": ["ltl", "truckload", "supply_chain_management"],
        "industries_served": ["manufacturing", "retail", "industrial", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["NC", "TX", "CA", "IL", "GA", "OH", "PA", "VA", "FL", "TN"],
    },
    {
        "company_name": "Echo Global Logistics",
        "headquarters_city": "Chicago",
        "headquarters_state": "IL",
        "website": "https://www.echo.com",
        "employee_count": 3500,
        "facility_count": 30,
        "services": ["freight_brokerage", "managed_transportation", "truckload", "ltl", "intermodal"],
        "industries_served": ["manufacturing", "retail", "food_beverage", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["IL", "TX", "CA", "GA", "OH", "PA", "IN", "FL", "NJ", "NC"],
    },
    {
        "company_name": "Knight-Swift Transportation",
        "headquarters_city": "Phoenix",
        "headquarters_state": "AZ",
        "website": "https://www.knight-swift.com",
        "employee_count": 25000,
        "facility_count": 120,
        "services": ["truckload", "ltl", "intermodal", "dedicated_transportation", "freight_brokerage"],
        "industries_served": ["retail", "manufacturing", "consumer_goods", "industrial"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["AZ", "TX", "CA", "IL", "GA", "OH", "PA", "IN", "TN", "FL"],
    },
    {
        "company_name": "Hub Group",
        "headquarters_city": "Oak Brook",
        "headquarters_state": "IL",
        "website": "https://www.hubgroup.com",
        "employee_count": 6100,
        "facility_count": 50,
        "services": ["intermodal", "truckload", "dedicated_transportation", "warehousing", "managed_transportation"],
        "industries_served": ["retail", "consumer_goods", "manufacturing", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["IL", "TX", "CA", "GA", "OH", "PA", "IN", "NJ", "FL", "TN"],
    },
    {
        "company_name": "Saia",
        "headquarters_city": "Johns Creek",
        "headquarters_state": "GA",
        "website": "https://www.saia.com",
        "employee_count": 13000,
        "facility_count": 213,
        "services": ["ltl", "truckload", "supply_chain_management"],
        "industries_served": ["manufacturing", "retail", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["GA", "TX", "CA", "IL", "OH", "PA", "NC", "FL", "VA", "TN"],
    },
    {
        "company_name": "Forward Air",
        "headquarters_city": "Greeneville",
        "headquarters_state": "TN",
        "website": "https://www.forwardair.com",
        "employee_count": 5500,
        "facility_count": 200,
        "services": ["ltl", "truckload", "intermodal", "final_mile", "freight_brokerage"],
        "industries_served": ["manufacturing", "retail", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["TN", "TX", "CA", "IL", "GA", "OH", "PA", "FL", "NC", "IN"],
    },
    {
        "company_name": "Radiant Logistics",
        "headquarters_city": "Bellevue",
        "headquarters_state": "WA",
        "website": "https://www.radiantdelivers.com",
        "employee_count": 4000,
        "facility_count": 100,
        "services": ["freight_forwarding", "customs_brokerage", "truckload", "ltl", "ocean", "air"],
        "industries_served": ["technology", "retail", "manufacturing", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America", "Global"],
        "states_coverage": ["WA", "CA", "TX", "IL", "GA", "OH", "PA", "NJ", "FL", "NY"],
    },
    {
        "company_name": "ArcBest",
        "headquarters_city": "Fort Smith",
        "headquarters_state": "AR",
        "website": "https://www.arcb.com",
        "employee_count": 14000,
        "facility_count": 250,
        "services": ["ltl", "truckload", "managed_transportation", "warehousing", "final_mile"],
        "industries_served": ["manufacturing", "retail", "industrial", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["AR", "TX", "CA", "IL", "GA", "OH", "PA", "FL", "IN", "TN"],
    },
    {
        "company_name": "Heartland Express",
        "headquarters_city": "North Liberty",
        "headquarters_state": "IA",
        "website": "https://www.heartlandexpress.com",
        "employee_count": 5500,
        "facility_count": 20,
        "services": ["truckload", "dedicated_transportation"],
        "industries_served": ["retail", "manufacturing", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["IA", "TX", "CA", "IL", "GA", "OH", "PA", "IN", "TN", "FL"],
    },
    {
        "company_name": "Lineage Logistics",
        "headquarters_city": "Novi",
        "headquarters_state": "MI",
        "website": "https://www.lineagelogistics.com",
        "employee_count": 26000,
        "facility_count": 480,
        "services": ["cold_storage", "warehousing", "transportation", "distribution"],
        "industries_served": ["food_beverage", "retail", "food_service", "agriculture"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Europe", "Asia Pacific"],
        "states_coverage": ["MI", "CA", "TX", "GA", "WA", "IL", "PA", "FL", "NJ", "OH"],
    },
    {
        "company_name": "NFI Industries",
        "headquarters_city": "Camden",
        "headquarters_state": "NJ",
        "website": "https://www.nfiindustries.com",
        "employee_count": 16000,
        "facility_count": 300,
        "services": ["dedicated_transportation", "warehousing", "distribution", "intermodal", "real_estate"],
        "industries_served": ["retail", "food_beverage", "consumer_goods", "manufacturing"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["NJ", "CA", "TX", "GA", "IL", "PA", "OH", "IN", "FL", "TN"],
    },
    {
        "company_name": "Total Quality Logistics",
        "headquarters_city": "Cincinnati",
        "headquarters_state": "OH",
        "website": "https://www.tql.com",
        "employee_count": 8500,
        "facility_count": 60,
        "services": ["freight_brokerage", "truckload", "ltl", "flatbed", "dedicated_transportation"],
        "industries_served": ["manufacturing", "retail", "construction", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["OH", "TX", "CA", "IL", "GA", "PA", "FL", "IN", "NC", "TN"],
    },
    {
        "company_name": "RXO",
        "headquarters_city": "Charlotte",
        "headquarters_state": "NC",
        "website": "https://www.rxo.com",
        "employee_count": 7500,
        "facility_count": 20,
        "services": ["freight_brokerage", "managed_transportation", "last_mile", "truckload"],
        "industries_served": ["retail", "ecommerce", "manufacturing", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["NC", "TX", "CA", "IL", "GA", "OH", "PA", "FL", "NJ", "IN"],
    },
    {
        "company_name": "Americold Realty Trust",
        "headquarters_city": "Atlanta",
        "headquarters_state": "GA",
        "website": "https://www.americold.com",
        "employee_count": 14000,
        "facility_count": 245,
        "services": ["cold_storage", "warehousing", "transportation", "distribution"],
        "industries_served": ["food_beverage", "retail", "food_service", "agriculture"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Europe", "Asia Pacific", "South America"],
        "states_coverage": ["GA", "CA", "TX", "IL", "PA", "OH", "WA", "FL", "IN", "WI"],
    },
    {
        "company_name": "Geodis",
        "headquarters_city": "Brentwood",
        "headquarters_state": "TN",
        "website": "https://www.geodis.com",
        "employee_count": 49000,
        "facility_count": 430,
        "services": ["freight_forwarding", "warehousing", "contract_logistics", "distribution", "supply_chain_management"],
        "industries_served": ["automotive", "technology", "retail", "healthcare", "industrial"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["TN", "TX", "CA", "IL", "GA", "OH", "PA", "NJ", "FL", "IN"],
    },
    {
        "company_name": "Kenco Logistics",
        "headquarters_city": "Chattanooga",
        "headquarters_state": "TN",
        "website": "https://www.kencogroup.com",
        "employee_count": 8000,
        "facility_count": 100,
        "services": ["warehousing", "distribution", "managed_transportation", "supply_chain_management"],
        "industries_served": ["consumer_goods", "food_beverage", "retail", "manufacturing"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["TN", "TX", "CA", "GA", "IL", "OH", "PA", "IN", "FL", "NC"],
    },
    {
        "company_name": "BNSF Logistics",
        "headquarters_city": "Springdale",
        "headquarters_state": "AR",
        "website": "https://www.bnsflogistics.com",
        "employee_count": 800,
        "facility_count": 15,
        "services": ["intermodal", "truckload", "ltl", "freight_brokerage", "managed_transportation"],
        "industries_served": ["manufacturing", "energy", "agriculture", "retail", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["AR", "TX", "CA", "IL", "GA", "WA", "OR", "KS", "NE", "MO"],
    },
    {
        "company_name": "Worldwide Express",
        "headquarters_city": "Dallas",
        "headquarters_state": "TX",
        "website": "https://www.wwex.com",
        "employee_count": 5000,
        "facility_count": 100,
        "services": ["ltl", "truckload", "freight_brokerage", "managed_transportation", "parcel"],
        "industries_served": ["manufacturing", "retail", "industrial", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["TX", "CA", "IL", "GA", "OH", "PA", "FL", "NJ", "NC", "IN"],
    },
    {
        "company_name": "Arrive Logistics",
        "headquarters_city": "Austin",
        "headquarters_state": "TX",
        "website": "https://www.arrivelogistics.com",
        "employee_count": 1500,
        "facility_count": 5,
        "services": ["freight_brokerage", "truckload", "ltl", "managed_transportation"],
        "industries_served": ["manufacturing", "retail", "food_beverage", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["TX", "CA", "IL", "GA", "OH", "PA", "FL", "IN", "NC", "TN"],
    },
    {
        "company_name": "Saddle Creek Logistics",
        "headquarters_city": "Lakeland",
        "headquarters_state": "FL",
        "website": "https://www.sclogistics.com",
        "employee_count": 4000,
        "facility_count": 50,
        "services": ["warehousing", "fulfillment", "transportation", "packaging"],
        "industries_served": ["consumer_goods", "retail", "food_beverage", "health_beauty"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["FL", "TX", "CA", "GA", "IL", "OH", "PA", "IN", "TN", "NC"],
    },
    {
        "company_name": "Coyote Logistics",
        "headquarters_city": "Chicago",
        "headquarters_state": "IL",
        "website": "https://www.coyote.com",
        "employee_count": 4000,
        "facility_count": 15,
        "services": ["freight_brokerage", "truckload", "ltl", "intermodal"],
        "industries_served": ["manufacturing", "retail", "consumer_goods", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["IL", "TX", "CA", "GA", "OH", "PA", "FL", "IN", "NC", "TN"],
    },
    {
        "company_name": "GlobalTranz",
        "headquarters_city": "Scottsdale",
        "headquarters_state": "AZ",
        "website": "https://www.globaltranz.com",
        "employee_count": 1500,
        "facility_count": 10,
        "services": ["freight_brokerage", "managed_transportation", "truckload", "ltl"],
        "industries_served": ["manufacturing", "retail", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["AZ", "TX", "CA", "IL", "GA", "OH", "PA", "FL", "NC", "IN"],
    },
    {
        "company_name": "Odyssey Logistics",
        "headquarters_city": "Danbury",
        "headquarters_state": "CT",
        "website": "https://www.odysseylogistics.com",
        "employee_count": 1000,
        "facility_count": 30,
        "services": ["managed_transportation", "intermodal", "freight_brokerage", "chemical_logistics"],
        "industries_served": ["chemical", "energy", "manufacturing", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["CT", "TX", "LA", "IL", "NJ", "OH", "PA", "GA", "CA", "WV"],
    },
    {
        "company_name": "Uber Freight",
        "headquarters_city": "Chicago",
        "headquarters_state": "IL",
        "website": "https://www.uberfreight.com",
        "employee_count": 3000,
        "facility_count": 10,
        "services": ["freight_brokerage", "truckload", "managed_transportation"],
        "industries_served": ["manufacturing", "retail", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America", "Europe"],
        "states_coverage": ["IL", "TX", "CA", "GA", "OH", "PA", "FL", "IN", "NC", "TN"],
    },
    {
        "company_name": "Transplace",
        "headquarters_city": "Frisco",
        "headquarters_state": "TX",
        "website": "https://www.transplace.com",
        "employee_count": 1300,
        "facility_count": 8,
        "services": ["managed_transportation", "freight_brokerage", "truckload", "ltl"],
        "industries_served": ["manufacturing", "retail", "consumer_goods", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["TX", "CA", "IL", "GA", "OH", "PA", "FL", "IN", "NC", "TN"],
    },
    {
        "company_name": "Averitt Express",
        "headquarters_city": "Cookeville",
        "headquarters_state": "TN",
        "website": "https://www.averittexpress.com",
        "employee_count": 8500,
        "facility_count": 130,
        "services": ["ltl", "truckload", "dedicated_transportation", "warehousing", "international"],
        "industries_served": ["manufacturing", "retail", "automotive", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["TN", "TX", "GA", "NC", "SC", "AL", "MS", "VA", "FL", "KY"],
    },
    {
        "company_name": "Estes Express Lines",
        "headquarters_city": "Richmond",
        "headquarters_state": "VA",
        "website": "https://www.estes-express.com",
        "employee_count": 22000,
        "facility_count": 280,
        "services": ["ltl", "truckload", "warehousing", "final_mile", "international"],
        "industries_served": ["manufacturing", "retail", "industrial", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["VA", "TX", "CA", "IL", "GA", "OH", "PA", "FL", "NC", "IN"],
    },
    {
        "company_name": "Southeastern Freight Lines",
        "headquarters_city": "Lexington",
        "headquarters_state": "SC",
        "website": "https://www.sefl.com",
        "employee_count": 10000,
        "facility_count": 90,
        "services": ["ltl", "truckload", "supply_chain_management"],
        "industries_served": ["manufacturing", "retail", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Southeast US"],
        "states_coverage": ["SC", "NC", "GA", "FL", "AL", "TN", "VA", "TX", "MS", "LA"],
    },
    {
        "company_name": "Nolan Transportation Group",
        "headquarters_city": "Kennesaw",
        "headquarters_state": "GA",
        "website": "https://www.ntgfreight.com",
        "employee_count": 1800,
        "facility_count": 15,
        "services": ["freight_brokerage", "truckload", "ltl", "managed_transportation"],
        "industries_served": ["manufacturing", "retail", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["GA", "TX", "CA", "IL", "OH", "PA", "FL", "NC", "TN", "IN"],
    },
    {
        "company_name": "R+L Carriers",
        "headquarters_city": "Wilmington",
        "headquarters_state": "OH",
        "website": "https://www.rlcarriers.com",
        "employee_count": 15000,
        "facility_count": 130,
        "services": ["ltl", "truckload", "warehousing", "last_mile"],
        "industries_served": ["manufacturing", "retail", "industrial", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["OH", "TX", "CA", "IL", "GA", "PA", "FL", "IN", "NC", "TN"],
    },
    {
        "company_name": "Ruan Transportation",
        "headquarters_city": "Des Moines",
        "headquarters_state": "IA",
        "website": "https://www.ruan.com",
        "employee_count": 6000,
        "facility_count": 100,
        "services": ["dedicated_transportation", "managed_transportation", "warehousing"],
        "industries_served": ["food_beverage", "manufacturing", "retail", "agriculture"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["IA", "TX", "CA", "IL", "GA", "OH", "PA", "MN", "MO", "IN"],
    },
    {
        "company_name": "Logistics Plus",
        "headquarters_city": "Erie",
        "headquarters_state": "PA",
        "website": "https://www.logisticsplus.com",
        "employee_count": 600,
        "facility_count": 40,
        "services": ["freight_forwarding", "warehousing", "customs_brokerage", "managed_transportation"],
        "industries_served": ["manufacturing", "technology", "retail", "energy"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America", "Europe", "Asia Pacific"],
        "states_coverage": ["PA", "TX", "CA", "IL", "OH", "GA", "NJ", "FL", "NY", "MI"],
    },
    {
        "company_name": "Performance Team",
        "headquarters_city": "Carson",
        "headquarters_state": "CA",
        "website": "https://www.performanceteam.net",
        "employee_count": 4500,
        "facility_count": 40,
        "services": ["warehousing", "distribution", "fulfillment", "transportation"],
        "industries_served": ["retail", "ecommerce", "consumer_goods", "food_beverage"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["CA", "TX", "GA", "NJ", "IL", "FL", "PA", "SC", "OH", "TN"],
    },
    {
        "company_name": "OmniTRAX",
        "headquarters_city": "Denver",
        "headquarters_state": "CO",
        "website": "https://www.omnitrax.com",
        "employee_count": 700,
        "facility_count": 25,
        "services": ["rail", "intermodal", "transloading", "warehousing"],
        "industries_served": ["energy", "agriculture", "manufacturing", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["CO", "TX", "IN", "OH", "GA", "IL", "OK", "KS", "WI", "MI"],
    },
    {
        "company_name": "Capacity",
        "headquarters_city": "Tuscaloosa",
        "headquarters_state": "AL",
        "website": "https://www.capacityllc.com",
        "employee_count": 3500,
        "facility_count": 40,
        "services": ["truckload", "dedicated_transportation", "warehousing"],
        "industries_served": ["manufacturing", "automotive", "retail"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["AL", "GA", "TN", "MS", "TX", "NC", "SC", "FL", "VA", "OH"],
    },
    {
        "company_name": "Alliance Shippers",
        "headquarters_city": "Keasbey",
        "headquarters_state": "NJ",
        "website": "https://www.alliance.com",
        "employee_count": 600,
        "facility_count": 15,
        "services": ["intermodal", "truckload", "ltl", "managed_transportation"],
        "industries_served": ["manufacturing", "retail", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["NJ", "CA", "TX", "IL", "GA", "OH", "PA", "FL", "NC", "IN"],
    },
    {
        "company_name": "Unyson",
        "headquarters_city": "St. Louis",
        "headquarters_state": "MO",
        "website": "https://www.unyson.com",
        "employee_count": 600,
        "facility_count": 5,
        "services": ["managed_transportation", "supply_chain_management", "freight_brokerage"],
        "industries_served": ["manufacturing", "retail", "consumer_goods", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["MO", "TX", "CA", "IL", "GA", "OH", "PA", "FL", "IN", "TN"],
    },
    {
        "company_name": "Rinchem Company",
        "headquarters_city": "Albuquerque",
        "headquarters_state": "NM",
        "website": "https://www.rinchem.com",
        "employee_count": 700,
        "facility_count": 20,
        "services": ["chemical_logistics", "warehousing", "transportation", "hazmat"],
        "industries_served": ["semiconductor", "chemical", "pharmaceutical", "technology"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Asia Pacific"],
        "states_coverage": ["NM", "TX", "CA", "AZ", "OR", "OH", "ID", "NY", "UT", "CO"],
    },
    {
        "company_name": "STG Logistics",
        "headquarters_city": "Overland Park",
        "headquarters_state": "KS",
        "website": "https://www.stgusa.com",
        "employee_count": 2500,
        "facility_count": 35,
        "services": ["intermodal", "truckload", "warehousing", "distribution"],
        "industries_served": ["retail", "manufacturing", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["KS", "CA", "TX", "IL", "GA", "OH", "NJ", "PA", "FL", "IN"],
    },
    {
        "company_name": "Sunset Transportation",
        "headquarters_city": "St. Louis",
        "headquarters_state": "MO",
        "website": "https://www.sunsettrans.com",
        "employee_count": 400,
        "facility_count": 8,
        "services": ["freight_brokerage", "managed_transportation", "truckload", "ltl"],
        "industries_served": ["manufacturing", "retail", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["MO", "IL", "TX", "CA", "OH", "GA", "PA", "IN", "FL", "KY"],
    },
    {
        "company_name": "CT Logistics",
        "headquarters_city": "Cleveland",
        "headquarters_state": "OH",
        "website": "https://www.ctlogistics.com",
        "employee_count": 300,
        "facility_count": 5,
        "services": ["freight_audit", "managed_transportation", "freight_brokerage"],
        "industries_served": ["manufacturing", "retail", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["OH", "TX", "CA", "IL", "GA", "PA", "FL", "IN", "NC", "MI"],
    },
    {
        "company_name": "Legacy Supply Chain",
        "headquarters_city": "Franklin",
        "headquarters_state": "TN",
        "website": "https://www.legacyscs.com",
        "employee_count": 5000,
        "facility_count": 40,
        "services": ["warehousing", "fulfillment", "transportation", "managed_transportation"],
        "industries_served": ["retail", "ecommerce", "consumer_goods", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["TN", "TX", "CA", "GA", "IL", "OH", "PA", "IN", "FL", "NC"],
    },
    {
        "company_name": "Omni Logistics",
        "headquarters_city": "Dallas",
        "headquarters_state": "TX",
        "website": "https://www.omnilogistics.com",
        "employee_count": 4000,
        "facility_count": 80,
        "services": ["freight_forwarding", "warehousing", "customs_brokerage", "air", "ocean"],
        "industries_served": ["technology", "aerospace", "energy", "manufacturing"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["TX", "CA", "IL", "GA", "OH", "NJ", "PA", "FL", "NY", "WA"],
    },
    {
        "company_name": "Transportation Insight",
        "headquarters_city": "Hickory",
        "headquarters_state": "NC",
        "website": "https://www.transportationinsight.com",
        "employee_count": 1500,
        "facility_count": 10,
        "services": ["managed_transportation", "freight_brokerage", "supply_chain_management"],
        "industries_served": ["manufacturing", "retail", "consumer_goods", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["NC", "TX", "CA", "GA", "IL", "OH", "PA", "FL", "IN", "TN"],
    },
    {
        "company_name": "Redwood Logistics",
        "headquarters_city": "Chicago",
        "headquarters_state": "IL",
        "website": "https://www.redwoodlogistics.com",
        "employee_count": 1000,
        "facility_count": 8,
        "services": ["freight_brokerage", "managed_transportation", "supply_chain_management", "ltl"],
        "industries_served": ["manufacturing", "retail", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["IL", "TX", "CA", "GA", "OH", "PA", "FL", "IN", "NC", "TN"],
    },
    {
        "company_name": "Pilot Freight Services",
        "headquarters_city": "Glen Mills",
        "headquarters_state": "PA",
        "website": "https://www.pilotdelivers.com",
        "employee_count": 2500,
        "facility_count": 80,
        "services": ["last_mile", "freight_forwarding", "warehousing", "white_glove"],
        "industries_served": ["retail", "ecommerce", "technology", "healthcare"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["PA", "TX", "CA", "IL", "GA", "OH", "NJ", "FL", "NC", "IN"],
    },
    {
        "company_name": "Dupre Logistics",
        "headquarters_city": "Lafayette",
        "headquarters_state": "LA",
        "website": "https://www.duprelogistics.com",
        "employee_count": 3000,
        "facility_count": 35,
        "services": ["dedicated_transportation", "warehousing", "chemical_logistics"],
        "industries_served": ["chemical", "energy", "manufacturing", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Gulf Coast", "Southeast US"],
        "states_coverage": ["LA", "TX", "MS", "AL", "GA", "SC", "TN", "AR", "FL", "NC"],
    },
    {
        "company_name": "Evans Transportation",
        "headquarters_city": "Kansas City",
        "headquarters_state": "MO",
        "website": "https://www.evanstrans.com",
        "employee_count": 300,
        "facility_count": 5,
        "services": ["freight_brokerage", "truckload", "ltl", "managed_transportation"],
        "industries_served": ["manufacturing", "retail", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["MO", "KS", "TX", "CA", "IL", "GA", "OH", "PA", "FL", "IN"],
    },
    {
        "company_name": "Prologis",
        "headquarters_city": "San Francisco",
        "headquarters_state": "CA",
        "website": "https://www.prologis.com",
        "employee_count": 2200,
        "facility_count": 5500,
        "services": ["warehousing", "distribution", "logistics_real_estate"],
        "industries_served": ["retail", "ecommerce", "manufacturing", "logistics"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["CA", "TX", "IL", "NJ", "PA", "GA", "OH", "IN", "FL", "TN"],
    },
    {
        "company_name": "XPO Logistics Europe",
        "headquarters_city": "Lyon",
        "headquarters_state": None,
        "website": "https://www.xpo.com",
        "employee_count": 43000,
        "facility_count": 300,
        "services": ["contract_logistics", "warehousing", "transportation", "distribution"],
        "industries_served": ["retail", "consumer_goods", "automotive", "technology"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Europe"],
    },
    {
        "company_name": "Syncreon",
        "headquarters_city": "Auburn Hills",
        "headquarters_state": "MI",
        "website": "https://www.syncreon.com",
        "employee_count": 14000,
        "facility_count": 85,
        "services": ["contract_logistics", "warehousing", "distribution", "fulfillment"],
        "industries_served": ["automotive", "technology", "aerospace", "healthcare"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Europe"],
        "states_coverage": ["MI", "TX", "CA", "IL", "GA", "OH", "PA", "IN", "TN", "SC"],
    },
    {
        "company_name": "Barrett Distribution Centers",
        "headquarters_city": "Franklin",
        "headquarters_state": "MA",
        "website": "https://www.barrettdistribution.com",
        "employee_count": 1500,
        "facility_count": 25,
        "services": ["warehousing", "fulfillment", "distribution", "ecommerce"],
        "industries_served": ["retail", "ecommerce", "consumer_goods", "health_beauty"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["MA", "CA", "TX", "NJ", "PA", "OH", "GA", "FL", "IL", "TN"],
    },
    {
        "company_name": "Purolator International",
        "headquarters_city": "Jericho",
        "headquarters_state": "NY",
        "website": "https://www.purolatorinternational.com",
        "employee_count": 12500,
        "facility_count": 200,
        "services": ["parcel", "freight_forwarding", "customs_brokerage", "warehousing"],
        "industries_served": ["ecommerce", "technology", "retail", "manufacturing"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["NY", "CA", "TX", "IL", "GA", "OH", "PA", "NJ", "FL", "MI"],
    },
    {
        "company_name": "SEKO Logistics",
        "headquarters_city": "Itasca",
        "headquarters_state": "IL",
        "website": "https://www.sekologistics.com",
        "employee_count": 3000,
        "facility_count": 120,
        "services": ["freight_forwarding", "warehousing", "fulfillment", "last_mile", "customs_brokerage"],
        "industries_served": ["retail", "ecommerce", "technology", "healthcare"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["IL", "CA", "TX", "GA", "OH", "NJ", "PA", "FL", "NY", "WA"],
    },
    {
        "company_name": "Bringg",
        "headquarters_city": "Chicago",
        "headquarters_state": "IL",
        "website": "https://www.bringg.com",
        "employee_count": 350,
        "facility_count": 5,
        "services": ["last_mile", "delivery_management", "fulfillment"],
        "industries_served": ["retail", "ecommerce", "food_delivery", "logistics"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["Global"],
        "states_coverage": ["IL", "CA", "TX", "NY", "GA", "FL", "PA", "OH", "NJ", "WA"],
    },
    {
        "company_name": "Port Logistics Group",
        "headquarters_city": "Kearny",
        "headquarters_state": "NJ",
        "website": "https://www.portlogisticsgroup.com",
        "employee_count": 3000,
        "facility_count": 30,
        "services": ["warehousing", "distribution", "fulfillment", "transloading"],
        "industries_served": ["retail", "ecommerce", "consumer_goods", "food_beverage"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["NJ", "CA", "GA", "TX", "IL", "PA", "OH", "FL", "SC", "WA"],
    },
    {
        "company_name": "Burris Logistics",
        "headquarters_city": "Milford",
        "headquarters_state": "DE",
        "website": "https://www.burrislogistics.com",
        "employee_count": 3500,
        "facility_count": 30,
        "services": ["cold_storage", "warehousing", "transportation", "distribution"],
        "industries_served": ["food_beverage", "food_service", "retail"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["East Coast"],
        "states_coverage": ["DE", "MD", "PA", "NJ", "VA", "NC", "GA", "FL", "SC", "NY"],
    },
    {
        "company_name": "RLS Logistics",
        "headquarters_city": "Newfield",
        "headquarters_state": "NJ",
        "website": "https://www.rlslogistics.com",
        "employee_count": 600,
        "facility_count": 10,
        "services": ["cold_storage", "warehousing", "transportation"],
        "industries_served": ["food_beverage", "food_service", "retail"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["East Coast"],
        "states_coverage": ["NJ", "PA", "DE", "MD", "VA", "NY", "CT", "FL", "GA", "SC"],
    },
    {
        "company_name": "Crane Worldwide Logistics",
        "headquarters_city": "Houston",
        "headquarters_state": "TX",
        "website": "https://www.craneww.com",
        "employee_count": 2000,
        "facility_count": 120,
        "services": ["freight_forwarding", "customs_brokerage", "ocean", "air", "warehousing"],
        "industries_served": ["energy", "aerospace", "manufacturing", "technology"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["TX", "CA", "IL", "GA", "OH", "NJ", "PA", "FL", "NY", "WA"],
    },
    {
        "company_name": "AM Transport Services",
        "headquarters_city": "Rogers",
        "headquarters_state": "AR",
        "website": "https://www.amtransportservices.com",
        "employee_count": 250,
        "facility_count": 5,
        "services": ["freight_brokerage", "truckload", "managed_transportation"],
        "industries_served": ["manufacturing", "retail", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["AR", "TX", "CA", "IL", "GA", "MO", "OK", "TN", "OH", "PA"],
    },
    {
        "company_name": "OHL",
        "headquarters_city": "Brentwood",
        "headquarters_state": "TN",
        "website": "https://www.ohl.com",
        "employee_count": 8000,
        "facility_count": 80,
        "services": ["contract_logistics", "warehousing", "distribution", "managed_transportation"],
        "industries_served": ["retail", "consumer_goods", "healthcare", "technology"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America", "Latin America"],
        "states_coverage": ["TN", "TX", "CA", "GA", "IL", "OH", "PA", "FL", "IN", "NC"],
    },
    {
        "company_name": "UniGroup Logistics",
        "headquarters_city": "Fenton",
        "headquarters_state": "MO",
        "website": "https://www.unigrouplogistics.com",
        "employee_count": 1000,
        "facility_count": 15,
        "services": ["managed_transportation", "warehousing", "final_mile", "white_glove"],
        "industries_served": ["retail", "ecommerce", "technology", "healthcare"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["MO", "TX", "CA", "IL", "GA", "OH", "PA", "FL", "IN", "NC"],
    },
    {
        "company_name": "AIT Worldwide Logistics",
        "headquarters_city": "Itasca",
        "headquarters_state": "IL",
        "website": "https://www.aitworldwide.com",
        "employee_count": 2500,
        "facility_count": 100,
        "services": ["freight_forwarding", "ocean", "air", "customs_brokerage", "warehousing"],
        "industries_served": ["technology", "retail", "manufacturing", "aerospace"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["Global"],
        "states_coverage": ["IL", "CA", "TX", "GA", "OH", "NJ", "PA", "FL", "NY", "WA"],
    },
    {
        "company_name": "Bolloré Logistics",
        "headquarters_city": "Miami",
        "headquarters_state": "FL",
        "website": "https://www.bollore-logistics.com",
        "employee_count": 35000,
        "facility_count": 600,
        "services": ["freight_forwarding", "ocean", "air", "contract_logistics", "customs_brokerage"],
        "industries_served": ["energy", "automotive", "retail", "aerospace", "pharmaceutical"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["FL", "TX", "CA", "IL", "GA", "NJ", "NY", "PA", "OH", "LA"],
    },
    {
        "company_name": "Dachser",
        "headquarters_city": "Atlanta",
        "headquarters_state": "GA",
        "website": "https://www.dachser.com",
        "employee_count": 31000,
        "facility_count": 400,
        "services": ["freight_forwarding", "ocean", "air", "contract_logistics", "warehousing"],
        "industries_served": ["automotive", "technology", "retail", "chemical", "industrial"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["GA", "CA", "TX", "IL", "OH", "NJ", "PA", "FL", "NY", "MI"],
    },
    {
        "company_name": "LoadSmart",
        "headquarters_city": "Chicago",
        "headquarters_state": "IL",
        "website": "https://www.loadsmart.com",
        "employee_count": 700,
        "facility_count": 5,
        "services": ["freight_brokerage", "truckload", "managed_transportation"],
        "industries_served": ["manufacturing", "retail", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["North America"],
        "states_coverage": ["IL", "TX", "CA", "GA", "OH", "PA", "FL", "NJ", "NY", "IN"],
    },
    {
        "company_name": "TA Services",
        "headquarters_city": "Cookeville",
        "headquarters_state": "TN",
        "website": "https://www.taservices.com",
        "employee_count": 1500,
        "facility_count": 30,
        "services": ["warehousing", "fulfillment", "transportation", "distribution"],
        "industries_served": ["retail", "ecommerce", "consumer_goods", "food_beverage"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Southeast US"],
        "states_coverage": ["TN", "GA", "TX", "NC", "SC", "AL", "FL", "VA", "OH", "IN"],
    },
    {
        "company_name": "Covenant Transport",
        "headquarters_city": "Chattanooga",
        "headquarters_state": "TN",
        "website": "https://www.covenantlogistics.com",
        "employee_count": 7000,
        "facility_count": 50,
        "services": ["truckload", "dedicated_transportation", "warehousing", "freight_brokerage"],
        "industries_served": ["retail", "manufacturing", "consumer_goods"],
        "has_cold_chain": True,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": False,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["TN", "TX", "CA", "GA", "OH", "IL", "PA", "FL", "IN", "NC"],
    },
    {
        "company_name": "Locus Logistics",
        "headquarters_city": "Winston-Salem",
        "headquarters_state": "NC",
        "website": "https://www.locuslogistics.com",
        "employee_count": 500,
        "facility_count": 10,
        "services": ["warehousing", "fulfillment", "distribution"],
        "industries_served": ["retail", "ecommerce", "consumer_goods"],
        "has_cold_chain": False,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Southeast US"],
        "states_coverage": ["NC", "GA", "SC", "VA", "TN", "FL", "TX", "OH", "PA", "IN"],
    },
    {
        "company_name": "ProTrans International",
        "headquarters_city": "Indianapolis",
        "headquarters_state": "IN",
        "website": "https://www.protrans.com",
        "employee_count": 1000,
        "facility_count": 15,
        "services": ["managed_transportation", "dedicated_transportation", "warehousing"],
        "industries_served": ["automotive", "manufacturing", "industrial"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["North America"],
        "states_coverage": ["IN", "OH", "MI", "TX", "GA", "IL", "TN", "KY", "PA", "NC"],
    },
    {
        "company_name": "Verst Logistics",
        "headquarters_city": "Walton",
        "headquarters_state": "KY",
        "website": "https://www.verstlogistics.com",
        "employee_count": 1200,
        "facility_count": 20,
        "services": ["warehousing", "fulfillment", "transportation", "packaging"],
        "industries_served": ["consumer_goods", "food_beverage", "retail", "ecommerce"],
        "has_cold_chain": True,
        "has_hazmat": False,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Midwest US", "East Coast"],
        "states_coverage": ["KY", "OH", "IN", "TN", "GA", "IL", "PA", "MI", "NC", "SC"],
    },
    {
        "company_name": "Dimerco Express Group",
        "headquarters_city": "New York",
        "headquarters_state": "NY",
        "website": "https://www.dimerco.com",
        "employee_count": 2600,
        "facility_count": 150,
        "services": ["freight_forwarding", "ocean", "air", "customs_brokerage", "warehousing"],
        "industries_served": ["technology", "retail", "automotive", "chemical"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": False,
        "has_cross_dock": True,
        "is_asset_based": False,
        "is_non_asset": True,
        "regions_served": ["Global"],
        "states_coverage": ["NY", "CA", "TX", "IL", "GA", "NJ", "OH", "PA", "FL", "WA"],
    },
    {
        "company_name": "Mallory Alexander International Logistics",
        "headquarters_city": "Memphis",
        "headquarters_state": "TN",
        "website": "https://www.mallorygroup.com",
        "employee_count": 600,
        "facility_count": 20,
        "services": ["freight_forwarding", "warehousing", "customs_brokerage", "ocean", "air"],
        "industries_served": ["manufacturing", "retail", "automotive", "healthcare"],
        "has_cold_chain": False,
        "has_hazmat": True,
        "has_ecommerce_fulfillment": True,
        "has_cross_dock": True,
        "is_asset_based": True,
        "is_non_asset": False,
        "regions_served": ["Global"],
        "states_coverage": ["TN", "TX", "CA", "GA", "IL", "OH", "PA", "NJ", "FL", "NY"],
    },
]
