"""
Skeleton tests for SPEC 041 — Metro Development Profiles Dataset
Generated by /spec skill. Fill in implementations before writing source code.
"""
import pytest


class TestMetroReference:
    """T1: metro_reference seeded with valid CBSAs."""

    def test_metro_reference_seeded(self):
        """T1: metro_reference has >= 400 rows with valid 5-digit CBSA codes."""
        pytest.skip("TODO: implement before writing source code")


class TestCensusBPSParser:
    """T2: Census BPS metro text file parser."""

    def test_bps_metro_parser(self):
        """T2: Census BPS metro text file parsed correctly for permits by unit type."""
        pytest.skip("TODO: implement before writing source code")


class TestFHFAFilter:
    """T3: FHFA CSV filtered to MSA geography."""

    def test_fhfa_msa_filter(self):
        """T3: FHFA CSV filtered to MSA geography type returns records with place_id."""
        pytest.skip("TODO: implement before writing source code")


class TestCensusACSCBSA:
    """T4: Census ACS CBSA-level queries."""

    def test_acs_cbsa_query(self):
        """T4: Census ACS returns population + income for a known CBSA."""
        pytest.skip("TODO: implement before writing source code")


class TestDerivedScores:
    """T5-T6: Derived score computation."""

    def test_derived_scores_range(self):
        """T5: All computed scores are 0.0–100.0."""
        pytest.skip("TODO: implement before writing source code")

    def test_build_hostility_composite(self):
        """T6: High price appreciation + low permit velocity -> high hostility score."""
        pytest.skip("TODO: implement before writing source code")


class TestMetroProfilesAPI:
    """T7-T10: API endpoint behavior."""

    def test_list_endpoint_paginated(self):
        """T7: /metro-profiles/ returns data array + total count."""
        pytest.skip("TODO: implement before writing source code")

    def test_detail_endpoint(self):
        """T8: /metro-profiles/35620 returns NYC with factor breakdown."""
        pytest.skip("TODO: implement before writing source code")

    def test_rankings_endpoint_sorted(self):
        """T9: /metro-profiles/rankings returns descending build_hostility_score."""
        pytest.skip("TODO: implement before writing source code")

    def test_graceful_missing_source(self):
        """T10: Metro with one missing source still returns partial profile with NULL columns."""
        pytest.skip("TODO: implement before writing source code")
