"""
Skeleton tests for SPEC 031 — Investor Intelligence API: Generalizable Report Data Layer
Generated by /spec skill. Fill in implementations before writing source code.
"""
import pytest


class TestSpec031InvestorIntelligence:
    """Tests for the Investor Intelligence API and supporting data sources."""

    def test_sectors_list_returns_all_nine(self):
        """T1: GET /investor/sectors returns 9 sectors with correct keys."""
        pytest.skip("TODO: implement — call GET /investor/sectors, assert 9 items, each has label/fred_categories/bls_datasets")

    def test_sector_detail_auto_service(self):
        """T2: GET /investor/sector/auto_service returns macro_indicators list."""
        pytest.skip("TODO: implement — call GET /investor/sector/auto_service, assert macro_indicators is list, sector key present")

    def test_sector_detail_unknown_slug(self):
        """T3: GET /investor/sector/nonexistent returns 404."""
        pytest.skip("TODO: implement — call GET /investor/sector/does_not_exist, assert 404 status code")

    def test_company_context_with_ticker(self):
        """T4: GET /investor/company/MNRO/context returns expected structure."""
        pytest.skip("TODO: implement — call GET /investor/company/MNRO/context, assert keys: company, ticker, job_trend, financials, sector_context")

    def test_company_context_unknown_ticker(self):
        """T5: GET /investor/company/ZZZZ/context returns 404 or empty gracefully."""
        pytest.skip("TODO: implement — call GET /investor/company/ZZZZ/context, assert 404 or empty structure (not 500)")

    def test_report_context_disruption(self):
        """T6: GET /investor/report-context/auto_service/disruption_analysis returns kpi_cards, chart_data."""
        pytest.skip("TODO: implement — call endpoint, assert response has kpi_cards (list of 5), chart_data (dict), narrative_context (str)")

    def test_report_context_invalid_question_type(self):
        """T7: Invalid question_type returns 400 with valid types listed."""
        pytest.skip("TODO: implement — call GET /investor/report-context/auto_service/bogus_type, assert 400 with valid_types in response")

    def test_afdc_ingest_returns_job_id(self):
        """T8: POST /afdc/ingest/ev_registrations returns job_id immediately."""
        pytest.skip("TODO: implement — POST /afdc/ingest/ev_registrations, assert response has job_id and status=pending/running")

    def test_fred_auto_sector_category_exists(self):
        """T9: COMMON_SERIES dict in fred/metadata.py has auto_sector key with TOTALSA."""
        from app.sources.fred.metadata import COMMON_SERIES
        assert "auto_sector" in COMMON_SERIES
        series_ids = [s["series_id"] for s in COMMON_SERIES["auto_sector"].values()]
        assert "TOTALSA" in series_ids

    def test_bls_auto_sector_dataset_exists(self):
        """T10: BLS metadata has auto_sector dataset with at least one CES series."""
        pytest.skip("TODO: implement — import BLS metadata, assert auto_sector key exists with series_ids list")
