"""
Skeleton tests for SPEC 049 — Phase A Data Prerequisites (W1 of PLAN_062).

Generated by /spec skill. Fill in implementations before writing source code.

Covers W1.A (SEC EDGAR XBRL bulk ingest), W1.B (FRED expansion + backfill),
W1.C (schema migration + v1 generator methodology fix).
"""
import pytest


class TestSpec049PhaseADataPrereqs:
    """Tests for Phase A data prerequisites — schema, ingest, v1 generator fixes."""

    # ------------------------------------------------------------------
    # W1.C — Schema migration: public_company_financials view
    # ------------------------------------------------------------------

    def test_public_company_financials_view_schema(self):
        """T1: View has exactly the columns v1 generator queries; types match."""
        pytest.skip("TODO: implement before writing source code")

    def test_public_company_financials_view_returns_data_after_ingest(self):
        """T2: Sample insert into sec_income_statement + NAICS metadata → view returns expected denormalized row."""
        pytest.skip("TODO: implement before writing source code")

    # ------------------------------------------------------------------
    # W1.C — Schema migration: fred_observations + backward-compat
    # ------------------------------------------------------------------

    def test_fred_observations_includes_all_series(self):
        """T3: After migration, all 7 existing interest-rate series + 5 new series are queryable from fred_observations."""
        pytest.skip("TODO: implement before writing source code")

    def test_fred_interest_rates_backward_compat_view(self):
        """T4: Old fred_interest_rates queries still return the same rows (view over new table)."""
        pytest.skip("TODO: implement before writing source code")

    # ------------------------------------------------------------------
    # W1.C — v1 generator methodology field fix
    # ------------------------------------------------------------------

    def test_v1_private_financials_reports_actual_mode_when_fitted(self):
        """T5: When peer query returns rows, methodology = 'peer_fitted_gaussian_copula'."""
        pytest.skip("TODO: implement before writing source code")

    def test_v1_private_financials_reports_fallback_when_no_peers(self):
        """T6: When peer query returns empty, methodology = 'sector_priors_fallback'."""
        pytest.skip("TODO: implement before writing source code")

    def test_v1_macro_scenarios_reports_actual_mode_when_calibrated(self):
        """T7: When FRED history > 24 months, methodology = 'fred_calibrated_ou_walk'."""
        pytest.skip("TODO: implement before writing source code")

    def test_v1_macro_scenarios_reports_fallback_when_no_history(self):
        """T8: When FRED query returns empty, methodology = 'default_params_fallback'."""
        pytest.skip("TODO: implement before writing source code")

    # ------------------------------------------------------------------
    # W1.A — SEC EDGAR XBRL bulk ingest
    # ------------------------------------------------------------------

    def test_sec_xbrl_ingest_respects_rate_limit(self):
        """T9: Mock SECClient verifies throttle calls keep us ≤ 10 req/sec (EDGAR limit)."""
        pytest.skip("TODO: implement before writing source code")

    def test_sec_xbrl_bulk_orchestrator_processes_cik_list(self):
        """T9b: Bulk orchestrator submits one ingest job per CIK and aggregates results."""
        pytest.skip("TODO: implement before writing source code")

    def test_cik_list_builder_returns_target_universe(self):
        """T9c: CIK list builder returns S&P 500 + Russell 2000 CIKs (~2,500) from EDGAR company_tickers.json."""
        pytest.skip("TODO: implement before writing source code")

    # ------------------------------------------------------------------
    # W1.B — FRED expansion + backfill
    # ------------------------------------------------------------------

    def test_fred_ingest_handles_new_series_in_config(self):
        """T10: Adding a new series_id to the FRED metadata triggers ingest into the correct category table without breaking existing."""
        pytest.skip("TODO: implement before writing source code")

    def test_fred_backfill_extends_history(self):
        """T10b: Triggering FRED ingest with observation_start=1965-01-01 upserts older rows without affecting recent ones."""
        pytest.skip("TODO: implement before writing source code")
