"""
State Economic Development Office (EDO) Incentive Programs Collector.

Curated seed data of ~65 major state incentive programs from publicly
available state EDO websites. No live API — this is reference data
for site selection scoring.

Sources: Texas EDF, JobsOhio, Georgia Quick Start, NC JDIG, etc.
"""

import logging
from datetime import datetime
from typing import Optional, Dict, Any, List

from sqlalchemy.orm import Session

from app.core.models_site_intel import IncentiveProgram
from app.sources.site_intel.base_collector import BaseCollector
from app.sources.site_intel.types import (
    SiteIntelDomain,
    SiteIntelSource,
    CollectionConfig,
    CollectionResult,
    CollectionStatus,
)
from app.sources.site_intel.runner import register_collector

logger = logging.getLogger(__name__)


# Curated incentive programs from major state EDOs
# All data sourced from publicly available state economic development websites
SEED_PROGRAMS: List[Dict[str, Any]] = [
    # --- Texas ---
    {
        "program_name": "Texas Enterprise Fund",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "Texas",
        "state": "TX",
        "target_industries": ["manufacturing", "technology", "aerospace", "energy"],
        "target_investments": ["manufacturing", "headquarters", "data_center"],
        "min_investment": 10000000,
        "min_jobs": 75,
        "max_benefit": 50000000,
        "benefit_duration_years": 1,
        "description": "Deal-closing fund for competitive projects creating high-value jobs in Texas.",
        "requirements": "Must demonstrate Texas is competing against another state for the project.",
        "application_url": "https://gov.texas.gov/business/page/texas-enterprise-fund",
        "source": "state_edo",
        "source_url": "https://gov.texas.gov/business",
    },
    {
        "program_name": "Texas Enterprise Zone Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Texas",
        "state": "TX",
        "target_industries": ["manufacturing", "distribution", "technology"],
        "target_investments": ["manufacturing", "warehouse"],
        "min_investment": None,
        "min_jobs": 25,
        "max_benefit": 2500000,
        "benefit_duration_years": 5,
        "description": "State sales and use tax refunds for qualified businesses in enterprise zones.",
        "requirements": "Must be in designated enterprise zone and create minimum jobs.",
        "application_url": "https://gov.texas.gov/business/page/enterprise-zone-program",
        "source": "state_edo",
        "source_url": "https://gov.texas.gov/business",
    },
    {
        "program_name": "Texas Skills Development Fund",
        "program_type": "training",
        "geography_type": "state",
        "geography_name": "Texas",
        "state": "TX",
        "target_industries": ["manufacturing", "technology", "healthcare"],
        "target_investments": ["manufacturing", "data_center"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": 500000,
        "benefit_duration_years": 2,
        "description": "Workforce training grants through community/technical colleges.",
        "requirements": "Partnership with local community or technical college required.",
        "application_url": "https://www.twc.texas.gov/partners/skills-development-fund",
        "source": "state_edo",
        "source_url": "https://www.twc.texas.gov",
    },
    {
        "program_name": "Chapter 313 (successor) Tax Limitation",
        "program_type": "abatement",
        "geography_type": "state",
        "geography_name": "Texas",
        "state": "TX",
        "target_industries": ["manufacturing", "energy", "technology"],
        "target_investments": ["manufacturing", "data_center", "energy"],
        "min_investment": 20000000,
        "min_jobs": 10,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Property tax limitations for qualifying large-scale capital investments.",
        "requirements": "Minimum investment threshold varies by school district.",
        "application_url": "https://comptroller.texas.gov/economy/local/ch313/",
        "source": "state_edo",
        "source_url": "https://comptroller.texas.gov",
    },
    # --- Ohio ---
    {
        "program_name": "JobsOhio Economic Development Grant",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "Ohio",
        "state": "OH",
        "target_industries": ["manufacturing", "technology", "logistics", "food_processing"],
        "target_investments": ["manufacturing", "headquarters", "data_center"],
        "min_investment": 500000,
        "min_jobs": 10,
        "max_benefit": 25000000,
        "benefit_duration_years": 3,
        "description": "Competitive grants for job-creating expansion and relocation projects.",
        "requirements": "Must create or retain jobs, demonstrate economic impact.",
        "application_url": "https://www.jobsohio.com/why-ohio/incentives",
        "source": "state_edo",
        "source_url": "https://www.jobsohio.com",
    },
    {
        "program_name": "Ohio Job Creation Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Ohio",
        "state": "OH",
        "target_industries": ["manufacturing", "technology", "financial_services"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": None,
        "min_jobs": 10,
        "max_benefit": None,
        "benefit_duration_years": 15,
        "description": "Refundable or nonrefundable tax credit based on Ohio income tax withholding of new employees.",
        "requirements": "Project must pay above county average wage.",
        "application_url": "https://development.ohio.gov/business/state-incentives/job-creation-tax-credit",
        "source": "state_edo",
        "source_url": "https://development.ohio.gov",
    },
    {
        "program_name": "Ohio Data Center Tax Exemption",
        "program_type": "abatement",
        "geography_type": "state",
        "geography_name": "Ohio",
        "state": "OH",
        "target_industries": ["technology"],
        "target_investments": ["data_center"],
        "min_investment": 100000000,
        "min_jobs": 20,
        "max_benefit": None,
        "benefit_duration_years": 15,
        "description": "Sales tax exemption on data center equipment purchases.",
        "requirements": "Minimum $100M investment and 20 new jobs.",
        "application_url": "https://development.ohio.gov/business/state-incentives",
        "source": "state_edo",
        "source_url": "https://development.ohio.gov",
    },
    # --- Georgia ---
    {
        "program_name": "Georgia Quick Start",
        "program_type": "training",
        "geography_type": "state",
        "geography_name": "Georgia",
        "state": "GA",
        "target_industries": ["manufacturing", "distribution", "technology"],
        "target_investments": ["manufacturing", "warehouse", "data_center"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 2,
        "description": "Free customized workforce training for new and expanding businesses.",
        "requirements": "Must be new or expanding operation in Georgia.",
        "application_url": "https://www.georgiaquickstart.org/",
        "source": "state_edo",
        "source_url": "https://www.georgia.org",
    },
    {
        "program_name": "Georgia Job Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Georgia",
        "state": "GA",
        "target_industries": ["manufacturing", "technology", "distribution"],
        "target_investments": ["manufacturing", "warehouse", "headquarters"],
        "min_investment": None,
        "min_jobs": 2,
        "max_benefit": None,
        "benefit_duration_years": 5,
        "description": "Tax credit up to $4,000 per new job per year for 5 years in Tier 1 counties.",
        "requirements": "Number of jobs varies by county tier (2-25 new jobs required).",
        "application_url": "https://www.georgia.org/competitive-advantages/incentives/tax-credits",
        "source": "state_edo",
        "source_url": "https://www.georgia.org",
    },
    {
        "program_name": "Georgia REBA Grant",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "Georgia",
        "state": "GA",
        "target_industries": ["manufacturing", "technology", "aerospace"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": 5000000,
        "min_jobs": 50,
        "max_benefit": 20000000,
        "benefit_duration_years": 1,
        "description": "Regional Economic Business Assistance grant for major projects.",
        "requirements": "Competitive application; must demonstrate significant economic impact.",
        "application_url": "https://www.georgia.org/competitive-advantages/incentives",
        "source": "state_edo",
        "source_url": "https://www.georgia.org",
    },
    # --- North Carolina ---
    {
        "program_name": "NC Job Development Investment Grant (JDIG)",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "North Carolina",
        "state": "NC",
        "target_industries": ["manufacturing", "technology", "financial_services"],
        "target_investments": ["manufacturing", "headquarters", "data_center"],
        "min_investment": 10000000,
        "min_jobs": 20,
        "max_benefit": 50000000,
        "benefit_duration_years": 12,
        "description": "Performance-based grant returning portion of new tax revenue generated by project.",
        "requirements": "Jobs must exceed county average wage; clawback provisions.",
        "application_url": "https://edpnc.com/incentives/job-development-investment-grant/",
        "source": "state_edo",
        "source_url": "https://edpnc.com",
    },
    {
        "program_name": "NC One North Carolina Fund",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "North Carolina",
        "state": "NC",
        "target_industries": ["manufacturing", "technology"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": 5000000,
        "benefit_duration_years": 1,
        "description": "Discretionary cash grant to attract business projects to NC.",
        "requirements": "Governor's discretion; competitive projects only.",
        "application_url": "https://edpnc.com/incentives/one-north-carolina-fund/",
        "source": "state_edo",
        "source_url": "https://edpnc.com",
    },
    # --- Florida ---
    {
        "program_name": "Florida Qualified Target Industry Tax Refund",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Florida",
        "state": "FL",
        "target_industries": ["manufacturing", "technology", "aerospace", "life_sciences"],
        "target_investments": ["manufacturing", "headquarters", "data_center"],
        "min_investment": None,
        "min_jobs": 10,
        "max_benefit": 3000000,
        "benefit_duration_years": 8,
        "description": "Tax refund of $3,000-$6,000 per new job created in target industries.",
        "requirements": "Must be in qualified target industry; wages must exceed area average.",
        "application_url": "https://www.floridajobs.org/business-growth-and-partnerships/for-businesses-702702702702702/qualified-target-industry",
        "source": "state_edo",
        "source_url": "https://www.enterpriseflorida.com",
    },
    {
        "program_name": "Florida Quick Response Training",
        "program_type": "training",
        "geography_type": "state",
        "geography_name": "Florida",
        "state": "FL",
        "target_industries": ["manufacturing", "technology", "distribution"],
        "target_investments": ["manufacturing", "warehouse"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": 250000,
        "benefit_duration_years": 1,
        "description": "Reimbursement grant for customized training for new or expanding businesses.",
        "requirements": "Must create permanent full-time jobs in Florida.",
        "application_url": "https://floridajobs.org/business-growth-and-partnerships/for-businesses-702702702702702/quick-response-training",
        "source": "state_edo",
        "source_url": "https://www.enterpriseflorida.com",
    },
    {
        "program_name": "Florida Capital Investment Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Florida",
        "state": "FL",
        "target_industries": ["manufacturing", "technology"],
        "target_investments": ["manufacturing", "data_center"],
        "min_investment": 25000000,
        "min_jobs": 100,
        "max_benefit": None,
        "benefit_duration_years": 20,
        "description": "Corporate income tax credit for large capital investment projects.",
        "requirements": "Minimum $25M investment and 100 jobs at 150% of area average wage.",
        "application_url": "https://www.enterpriseflorida.com/incentives/",
        "source": "state_edo",
        "source_url": "https://www.enterpriseflorida.com",
    },
    # --- Indiana ---
    {
        "program_name": "Indiana Economic Development for a Growing Economy (EDGE)",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Indiana",
        "state": "IN",
        "target_industries": ["manufacturing", "technology", "logistics"],
        "target_investments": ["manufacturing", "headquarters", "warehouse"],
        "min_investment": None,
        "min_jobs": 10,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Refundable tax credit based on projected income tax withholdings of new employees.",
        "requirements": "Must pay above average wage for county; performance-based.",
        "application_url": "https://www.iedc.in.gov/incentives/economic-development-for-a-growing-economy",
        "source": "state_edo",
        "source_url": "https://www.iedc.in.gov",
    },
    {
        "program_name": "Indiana Hoosier Business Investment Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Indiana",
        "state": "IN",
        "target_industries": ["manufacturing", "logistics"],
        "target_investments": ["manufacturing", "warehouse"],
        "min_investment": 1000000,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Income tax credit based on qualified capital investment in Indiana.",
        "requirements": "Must make qualifying capital investment; applied against tax liability.",
        "application_url": "https://www.iedc.in.gov/incentives/hoosier-business-investment-tax-credit",
        "source": "state_edo",
        "source_url": "https://www.iedc.in.gov",
    },
    # --- Tennessee ---
    {
        "program_name": "Tennessee FastTrack Economic Development Fund",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "Tennessee",
        "state": "TN",
        "target_industries": ["manufacturing", "technology", "distribution"],
        "target_investments": ["manufacturing", "headquarters", "warehouse"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": 15000000,
        "benefit_duration_years": 3,
        "description": "Discretionary incentive for job creation, infrastructure, and training.",
        "requirements": "Must be a net-new project; performance milestones required.",
        "application_url": "https://www.tnecd.com/advantages/incentives/",
        "source": "state_edo",
        "source_url": "https://www.tnecd.com",
    },
    {
        "program_name": "Tennessee Job Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Tennessee",
        "state": "TN",
        "target_industries": ["manufacturing", "distribution", "technology"],
        "target_investments": ["manufacturing", "warehouse"],
        "min_investment": None,
        "min_jobs": 25,
        "max_benefit": None,
        "benefit_duration_years": 3,
        "description": "Tax credit of $4,500 per job in Tier 2/3 enhancement counties.",
        "requirements": "Minimum job creation varies by county tier.",
        "application_url": "https://www.tnecd.com/advantages/incentives/",
        "source": "state_edo",
        "source_url": "https://www.tnecd.com",
    },
    # --- South Carolina ---
    {
        "program_name": "SC Job Development Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "South Carolina",
        "state": "SC",
        "target_industries": ["manufacturing", "technology", "distribution"],
        "target_investments": ["manufacturing", "warehouse", "data_center"],
        "min_investment": 2500000,
        "min_jobs": 10,
        "max_benefit": None,
        "benefit_duration_years": 15,
        "description": "Rebate of withholding taxes for eligible new or expanding businesses.",
        "requirements": "Must invest minimum $2.5M and create 10+ jobs.",
        "application_url": "https://www.sccommerce.com/incentives",
        "source": "state_edo",
        "source_url": "https://www.sccommerce.com",
    },
    {
        "program_name": "SC readySC Training",
        "program_type": "training",
        "geography_type": "state",
        "geography_name": "South Carolina",
        "state": "SC",
        "target_industries": ["manufacturing", "technology", "automotive"],
        "target_investments": ["manufacturing"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 2,
        "description": "Free customized workforce recruitment, assessment, and training.",
        "requirements": "Must be new or expanding operation creating production-level jobs.",
        "application_url": "https://www.readysc.org/",
        "source": "state_edo",
        "source_url": "https://www.sccommerce.com",
    },
    # --- Virginia ---
    {
        "program_name": "Virginia Jobs Investment Program",
        "program_type": "training",
        "geography_type": "state",
        "geography_name": "Virginia",
        "state": "VA",
        "target_industries": ["manufacturing", "technology", "distribution"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": None,
        "min_jobs": 5,
        "max_benefit": 500000,
        "benefit_duration_years": 2,
        "description": "Funding for customized recruitment and training for new and expanding companies.",
        "requirements": "Minimum 5 new full-time jobs; must pay above minimum wage.",
        "application_url": "https://www.vedp.org/incentive/virginia-jobs-investment-program-vjip",
        "source": "state_edo",
        "source_url": "https://www.vedp.org",
    },
    {
        "program_name": "Virginia Economic Development Incentive Grant (VEDIG)",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "Virginia",
        "state": "VA",
        "target_industries": ["manufacturing", "technology"],
        "target_investments": ["manufacturing", "headquarters", "data_center"],
        "min_investment": 25000000,
        "min_jobs": 200,
        "max_benefit": 25000000,
        "benefit_duration_years": 5,
        "description": "Performance-based grant for major employers creating 200+ jobs.",
        "requirements": "Minimum $25M investment and 200 jobs; must compete against another state.",
        "application_url": "https://www.vedp.org/incentive/virginia-economic-development-incentive-grant-vedig",
        "source": "state_edo",
        "source_url": "https://www.vedp.org",
    },
    # --- Michigan ---
    {
        "program_name": "Michigan Business Development Program",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "Michigan",
        "state": "MI",
        "target_industries": ["manufacturing", "automotive", "technology"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": None,
        "min_jobs": 50,
        "max_benefit": 10000000,
        "benefit_duration_years": 5,
        "description": "Performance-based grants for significant job creation projects.",
        "requirements": "Minimum 50 new jobs; must demonstrate competitive need.",
        "application_url": "https://www.michiganbusiness.org/services/economic-development-incentives/",
        "source": "state_edo",
        "source_url": "https://www.michiganbusiness.org",
    },
    {
        "program_name": "Michigan SOAR Fund",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "Michigan",
        "state": "MI",
        "target_industries": ["manufacturing", "ev", "semiconductor"],
        "target_investments": ["manufacturing"],
        "min_investment": 250000000,
        "min_jobs": 500,
        "max_benefit": 200000000,
        "benefit_duration_years": 10,
        "description": "Strategic site readiness fund for transformational projects.",
        "requirements": "Mega-project scale; site preparation and infrastructure.",
        "application_url": "https://www.michiganbusiness.org/services/economic-development-incentives/",
        "source": "state_edo",
        "source_url": "https://www.michiganbusiness.org",
    },
    # --- Pennsylvania ---
    {
        "program_name": "PA Keystone Opportunity Zone",
        "program_type": "abatement",
        "geography_type": "state",
        "geography_name": "Pennsylvania",
        "state": "PA",
        "target_industries": ["manufacturing", "technology", "logistics"],
        "target_investments": ["manufacturing", "warehouse", "data_center"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "State and local tax abatement in designated underutilized zones.",
        "requirements": "Must locate in designated KOZ/KOEZ/KOZEZ area.",
        "application_url": "https://dced.pa.gov/programs/keystone-opportunity-zone-tax-program-koz/",
        "source": "state_edo",
        "source_url": "https://dced.pa.gov",
    },
    {
        "program_name": "PA Manufacturing Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Pennsylvania",
        "state": "PA",
        "target_industries": ["manufacturing"],
        "target_investments": ["manufacturing"],
        "min_investment": None,
        "min_jobs": 25,
        "max_benefit": 2000000,
        "benefit_duration_years": 5,
        "description": "Tax credit for manufacturing companies creating new jobs in PA.",
        "requirements": "Must be SIC manufacturing code; create 25+ new jobs.",
        "application_url": "https://dced.pa.gov/programs/",
        "source": "state_edo",
        "source_url": "https://dced.pa.gov",
    },
    # --- Arizona ---
    {
        "program_name": "Arizona Quality Jobs Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Arizona",
        "state": "AZ",
        "target_industries": ["manufacturing", "technology", "aerospace"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": 5000000,
        "min_jobs": 25,
        "max_benefit": None,
        "benefit_duration_years": 5,
        "description": "Income tax credit for creating quality jobs paying above county median.",
        "requirements": "$5M+ capital investment and 25+ jobs above county median wage.",
        "application_url": "https://www.azcommerce.com/incentives/quality-jobs-tax-credit/",
        "source": "state_edo",
        "source_url": "https://www.azcommerce.com",
    },
    {
        "program_name": "Arizona Data Center Tax Incentive",
        "program_type": "abatement",
        "geography_type": "state",
        "geography_name": "Arizona",
        "state": "AZ",
        "target_industries": ["technology"],
        "target_investments": ["data_center"],
        "min_investment": 50000000,
        "min_jobs": 25,
        "max_benefit": None,
        "benefit_duration_years": 20,
        "description": "Transaction privilege (sales) tax exemption on data center equipment.",
        "requirements": "$50M+ investment and 25+ new jobs.",
        "application_url": "https://www.azcommerce.com/incentives/",
        "source": "state_edo",
        "source_url": "https://www.azcommerce.com",
    },
    # --- Nevada ---
    {
        "program_name": "Nevada Governor's Office of Economic Development Tax Abatement",
        "program_type": "abatement",
        "geography_type": "state",
        "geography_name": "Nevada",
        "state": "NV",
        "target_industries": ["manufacturing", "technology", "logistics", "energy"],
        "target_investments": ["manufacturing", "data_center", "warehouse"],
        "min_investment": 1000000,
        "min_jobs": 50,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Partial sales tax and property tax abatements for qualified projects.",
        "requirements": "Must invest $1M+ and create 50+ jobs paying 100% of county average.",
        "application_url": "https://goed.nv.gov/programs-incentives/",
        "source": "state_edo",
        "source_url": "https://goed.nv.gov",
    },
    # --- Alabama ---
    {
        "program_name": "Alabama Jobs Act",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Alabama",
        "state": "AL",
        "target_industries": ["manufacturing", "automotive", "aerospace"],
        "target_investments": ["manufacturing"],
        "min_investment": 2000000,
        "min_jobs": 50,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Cash rebate of up to 3% of prior-year wages for qualifying projects.",
        "requirements": "Minimum 50 jobs and $2M investment; tiered by project size.",
        "application_url": "https://www.madeinalabama.com/why-alabama/incentives/",
        "source": "state_edo",
        "source_url": "https://www.madeinalabama.com",
    },
    {
        "program_name": "Alabama Industrial Development Training (AIDT)",
        "program_type": "training",
        "geography_type": "state",
        "geography_name": "Alabama",
        "state": "AL",
        "target_industries": ["manufacturing", "automotive"],
        "target_investments": ["manufacturing"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 2,
        "description": "Free customized pre-employment and on-the-job training.",
        "requirements": "Must be new or expanding manufacturer in Alabama.",
        "application_url": "https://www.aidt.edu/",
        "source": "state_edo",
        "source_url": "https://www.madeinalabama.com",
    },
    # --- Mississippi ---
    {
        "program_name": "Mississippi Advantage Jobs Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Mississippi",
        "state": "MS",
        "target_industries": ["manufacturing", "technology", "distribution"],
        "target_investments": ["manufacturing", "warehouse", "data_center"],
        "min_investment": None,
        "min_jobs": 25,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Income tax rebate for qualifying businesses creating high-wage jobs.",
        "requirements": "Must create 25+ full-time jobs paying 110% of state average.",
        "application_url": "https://mississippi.org/incentives-and-financing/",
        "source": "state_edo",
        "source_url": "https://mississippi.org",
    },
    # --- Louisiana ---
    {
        "program_name": "Louisiana Industrial Tax Exemption Program (ITEP)",
        "program_type": "abatement",
        "geography_type": "state",
        "geography_name": "Louisiana",
        "state": "LA",
        "target_industries": ["manufacturing", "energy", "chemical"],
        "target_investments": ["manufacturing"],
        "min_investment": 5000000,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Property tax abatement on manufacturing improvements and equipment.",
        "requirements": "Must be classified as manufacturer; local approval required.",
        "application_url": "https://www.opportunitylouisiana.gov/business-incentives/industrial-tax-exemption",
        "source": "state_edo",
        "source_url": "https://www.opportunitylouisiana.gov",
    },
    {
        "program_name": "Louisiana Quality Jobs Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Louisiana",
        "state": "LA",
        "target_industries": ["manufacturing", "technology", "energy"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": None,
        "min_jobs": 5,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Cash rebate of up to 6% of annual gross payroll for qualifying jobs.",
        "requirements": "Must create 5+ new permanent jobs at minimum wage thresholds.",
        "application_url": "https://www.opportunitylouisiana.gov/business-incentives/quality-jobs",
        "source": "state_edo",
        "source_url": "https://www.opportunitylouisiana.gov",
    },
    # --- Kentucky ---
    {
        "program_name": "Kentucky Business Investment Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Kentucky",
        "state": "KY",
        "target_industries": ["manufacturing", "technology", "logistics"],
        "target_investments": ["manufacturing", "headquarters", "warehouse"],
        "min_investment": 100000,
        "min_jobs": 10,
        "max_benefit": None,
        "benefit_duration_years": 15,
        "description": "Tax credits against income tax and wage assessments for new investment.",
        "requirements": "Must create 10+ jobs and invest minimum $100K.",
        "application_url": "https://ced.ky.gov/Incentives/KBI",
        "source": "state_edo",
        "source_url": "https://ced.ky.gov",
    },
    # --- Illinois ---
    {
        "program_name": "Illinois EDGE Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Illinois",
        "state": "IL",
        "target_industries": ["manufacturing", "technology", "logistics"],
        "target_investments": ["manufacturing", "headquarters", "warehouse"],
        "min_investment": None,
        "min_jobs": 25,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Income tax credit based on payroll of net new jobs.",
        "requirements": "Must create 25+ new full-time jobs (10 in underserved areas).",
        "application_url": "https://dceo.illinois.gov/expandrelocate/incentives/edgetaxcredit.html",
        "source": "state_edo",
        "source_url": "https://dceo.illinois.gov",
    },
    # --- Colorado ---
    {
        "program_name": "Colorado Job Growth Incentive Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Colorado",
        "state": "CO",
        "target_industries": ["technology", "aerospace", "manufacturing", "energy"],
        "target_investments": ["headquarters", "manufacturing"],
        "min_investment": None,
        "min_jobs": 20,
        "max_benefit": None,
        "benefit_duration_years": 8,
        "description": "Performance-based income tax credit for net new jobs.",
        "requirements": "Must create 20+ net new jobs; competitive application.",
        "application_url": "https://oedit.colorado.gov/job-growth-incentive-tax-credit",
        "source": "state_edo",
        "source_url": "https://oedit.colorado.gov",
    },
    # --- Wisconsin ---
    {
        "program_name": "Wisconsin Enterprise Zone Tax Credit",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Wisconsin",
        "state": "WI",
        "target_industries": ["manufacturing", "technology"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 12,
        "description": "Refundable tax credits for job creation, capital investment, and training.",
        "requirements": "Must be in designated Enterprise Zone; negotiated per-project.",
        "application_url": "https://wedc.org/programs-and-resources/enterprise-zone-tax-credit/",
        "source": "state_edo",
        "source_url": "https://wedc.org",
    },
    # --- Missouri ---
    {
        "program_name": "Missouri Works Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Missouri",
        "state": "MO",
        "target_industries": ["manufacturing", "technology", "distribution"],
        "target_investments": ["manufacturing", "headquarters", "warehouse"],
        "min_investment": None,
        "min_jobs": 2,
        "max_benefit": None,
        "benefit_duration_years": 5,
        "description": "Withholding tax retention for new job creation based on wage levels.",
        "requirements": "Must create new jobs above county average wage.",
        "application_url": "https://ded.mo.gov/programs/business/missouri-works",
        "source": "state_edo",
        "source_url": "https://ded.mo.gov",
    },
    # --- Iowa ---
    {
        "program_name": "Iowa High Quality Jobs Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Iowa",
        "state": "IA",
        "target_industries": ["manufacturing", "technology", "biosciences"],
        "target_investments": ["manufacturing", "data_center"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Tax incentives including investment tax credits and sales tax refunds.",
        "requirements": "Must pay qualifying wage threshold; industry must qualify.",
        "application_url": "https://www.iowaeda.com/incentive-programs/high-quality-jobs/",
        "source": "state_edo",
        "source_url": "https://www.iowaeda.com",
    },
    # --- New York ---
    {
        "program_name": "New York Excelsior Jobs Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "New York",
        "state": "NY",
        "target_industries": ["technology", "manufacturing", "financial_services", "life_sciences"],
        "target_investments": ["manufacturing", "headquarters", "data_center"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Refundable tax credits for job creation, investment, and R&D in strategic industries.",
        "requirements": "Must be in approved industry; net new jobs required.",
        "application_url": "https://esd.ny.gov/excelsior-jobs-program",
        "source": "state_edo",
        "source_url": "https://esd.ny.gov",
    },
    # --- New Jersey ---
    {
        "program_name": "New Jersey Aspire Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "New Jersey",
        "state": "NJ",
        "target_industries": ["technology", "manufacturing", "life_sciences"],
        "target_investments": ["headquarters", "manufacturing", "data_center"],
        "min_investment": None,
        "min_jobs": 25,
        "max_benefit": None,
        "benefit_duration_years": 7,
        "description": "Tax credits for businesses creating or retaining jobs in New Jersey.",
        "requirements": "Must demonstrate net positive economic benefit to state.",
        "application_url": "https://www.njeda.gov/aspire/",
        "source": "state_edo",
        "source_url": "https://www.njeda.gov",
    },
    # --- Washington ---
    {
        "program_name": "Washington Data Center Sales Tax Exemption",
        "program_type": "abatement",
        "geography_type": "state",
        "geography_name": "Washington",
        "state": "WA",
        "target_industries": ["technology"],
        "target_investments": ["data_center"],
        "min_investment": None,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": None,
        "description": "Sales and use tax exemption for eligible data center equipment and power.",
        "requirements": "Must be qualifying data center in eligible rural county.",
        "application_url": "https://choosewashingtonstate.com/i-need-help-with/site-selection/data-centers/",
        "source": "state_edo",
        "source_url": "https://choosewashingtonstate.com",
    },
    # --- Nebraska ---
    {
        "program_name": "Nebraska ImagiNE Act",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Nebraska",
        "state": "NE",
        "target_industries": ["manufacturing", "technology", "logistics"],
        "target_investments": ["manufacturing", "data_center", "warehouse"],
        "min_investment": 1000000,
        "min_jobs": 10,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Tiered tax incentives based on investment and job creation levels.",
        "requirements": "Multiple tiers based on investment ($1M-$100M+) and jobs (10-500+).",
        "application_url": "https://opportunity.nebraska.gov/incentives/imagine-nebraska-act/",
        "source": "state_edo",
        "source_url": "https://opportunity.nebraska.gov",
    },
    # --- Kansas ---
    {
        "program_name": "Kansas PEAK (Promoting Employment Across Kansas)",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Kansas",
        "state": "KS",
        "target_industries": ["manufacturing", "technology", "aviation"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": None,
        "min_jobs": 5,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Retention of 95% of payroll withholding tax for net new jobs.",
        "requirements": "Must create 5+ net new jobs; industry must qualify.",
        "application_url": "https://www.kansascommerce.gov/program/taxes-and-financing/peak/",
        "source": "state_edo",
        "source_url": "https://www.kansascommerce.gov",
    },
    # --- Oklahoma ---
    {
        "program_name": "Oklahoma Quality Jobs Program",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Oklahoma",
        "state": "OK",
        "target_industries": ["manufacturing", "technology", "energy"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": 2500000,
        "min_jobs": None,
        "max_benefit": None,
        "benefit_duration_years": 10,
        "description": "Cash payments of up to 5% of new taxable payroll for qualifying companies.",
        "requirements": "Quarterly payroll of $2.5M+ with average wages above threshold.",
        "application_url": "https://www.okcommerce.gov/doing-business/incentives-financing/quality-jobs-program/",
        "source": "state_edo",
        "source_url": "https://www.okcommerce.gov",
    },
    # --- Utah ---
    {
        "program_name": "Utah Economic Development Tax Increment Financing",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Utah",
        "state": "UT",
        "target_industries": ["technology", "manufacturing", "life_sciences"],
        "target_investments": ["headquarters", "manufacturing", "data_center"],
        "min_investment": None,
        "min_jobs": 50,
        "max_benefit": None,
        "benefit_duration_years": 20,
        "description": "Post-performance tax credit rebate based on new state tax revenue generated.",
        "requirements": "Minimum 50 new jobs; competitive application through GOED.",
        "application_url": "https://business.utah.gov/economic-development-tax-increment-financing-edtif/",
        "source": "state_edo",
        "source_url": "https://business.utah.gov",
    },
    # --- Minnesota ---
    {
        "program_name": "Minnesota Job Creation Fund",
        "program_type": "grant",
        "geography_type": "state",
        "geography_name": "Minnesota",
        "state": "MN",
        "target_industries": ["manufacturing", "technology", "biosciences"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": 500000,
        "min_jobs": 10,
        "max_benefit": 2000000,
        "benefit_duration_years": 5,
        "description": "Performance-based grant tied to meeting investment and job creation goals.",
        "requirements": "Must invest $500K+ and create 10+ full-time jobs.",
        "application_url": "https://mn.gov/deed/business/financing-business/deed-programs/job-creation-fund/",
        "source": "state_edo",
        "source_url": "https://mn.gov/deed",
    },
    # --- Idaho ---
    {
        "program_name": "Idaho Tax Reimbursement Incentive",
        "program_type": "tax_credit",
        "geography_type": "state",
        "geography_name": "Idaho",
        "state": "ID",
        "target_industries": ["manufacturing", "technology", "food_processing"],
        "target_investments": ["manufacturing", "headquarters"],
        "min_investment": 500000,
        "min_jobs": 20,
        "max_benefit": None,
        "benefit_duration_years": 15,
        "description": "Reimbursement of up to 30% of income/payroll taxes generated by new project.",
        "requirements": "Must create 20+ jobs and invest $500K+.",
        "application_url": "https://commerce.idaho.gov/incentives/tax-reimbursement-incentive/",
        "source": "state_edo",
        "source_url": "https://commerce.idaho.gov",
    },
]


@register_collector(SiteIntelSource.STATE_EDO)
class StateEDOIncentiveCollector(BaseCollector):
    """
    Collector for state economic development office incentive programs.

    Uses curated seed data from publicly available state EDO websites.
    No live API calls — this provides a reference dataset of major
    state incentive programs relevant to industrial site selection.
    """

    domain = SiteIntelDomain.INCENTIVES
    source = SiteIntelSource.STATE_EDO

    def __init__(self, db: Session, api_key: Optional[str] = None, **kwargs):
        super().__init__(db, api_key, **kwargs)

    def get_default_base_url(self) -> str:
        return ""  # No API — seed data

    async def collect(self, config: CollectionConfig) -> CollectionResult:
        """Load curated incentive program seed data."""
        try:
            programs = SEED_PROGRAMS

            # Filter by states if specified
            if config.states:
                state_set = set(config.states)
                programs = [p for p in programs if p["state"] in state_set]

            if not programs:
                return self.create_result(
                    status=CollectionStatus.SUCCESS,
                    total=0,
                    processed=0,
                    inserted=0,
                )

            # Add collected_at timestamp
            records = []
            for program in programs:
                record = {**program, "collected_at": datetime.utcnow()}
                records.append(record)

            logger.info(f"Loading {len(records)} incentive programs from seed data")

            inserted, updated = self.bulk_upsert(
                IncentiveProgram,
                records,
                unique_columns=["program_name", "state"],
                update_columns=[
                    "program_type", "geography_type", "geography_name",
                    "target_industries", "target_investments",
                    "min_investment", "min_jobs", "max_benefit",
                    "benefit_duration_years", "description", "requirements",
                    "application_url", "source", "source_url", "collected_at",
                ],
            )

            return self.create_result(
                status=CollectionStatus.SUCCESS,
                total=len(programs),
                processed=len(records),
                inserted=inserted + updated,
            )

        except Exception as e:
            logger.error(f"State EDO collection failed: {e}", exc_info=True)
            return self.create_result(
                status=CollectionStatus.FAILED,
                error_message=str(e),
            )
