"""
Synthetic Playground Report — shareable artifact for the free playground.

Turns a synthetic-generator run into a polished, self-contained HTML report
carrying a "Made with Nexdata" CTA. This is the viral loop's payload: a
recipient opens a forwarded `/p/<short_code>` URL, sees credible synthetic
output, and the CTA routes them toward the enterprise platform.

The playground router (SPEC_056 Step 6) owns generator-output → normalized
payload translation; this template only renders the normalized payload:

    {
      "generator": "macro-scenarios",
      "generator_label": "Macro Scenario Paths",
      "request_params": {...},
      "summary": {"Scenarios": 100, "Horizon": "24 mo", ...},
      "rows": [{"col": val, ...}, ...],          # sample, <=20 shown
      "chart": {"labels": [...], "series": [{"label","data"}], "y_label": ""} | None,
    }

PLAN_063 C5 + C7 (CTA folded in — it is the growth mechanism, not deferred).
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

from sqlalchemy.orm import Session

from app.reports.design_system import (
    BLUE, CHART_COLORS, GRAY, GREEN, TEAL,
    build_bar_fallback, build_line_chart_config,
    callout, chart_container, chart_init_js,
    data_table, html_document, kpi_card, kpi_strip,
    page_footer, page_header, section_end, section_start,
)
from app.reports.templates._ic_report_base import ICReportBase

logger = logging.getLogger(__name__)


# CTA copy — the growth mechanism. Stable text so Step 6/8 can reason about it.
CTA_HEADLINE = (
    "Made with Nexdata — this is a synthetic sample. "
    "The full platform runs on your real data."
)
CTA_SUBCOPY = (
    "Underwriting, datacenter, energy, and litigation-finance teams use Nexdata "
    "for production intelligence."
)

# generator -> most-relevant enterprise vertical hint (for the CTA deep-link copy)
_VERTICAL_HINT = {
    "private-financials": "insurance underwriting & litigation finance",
    "macro-scenarios": "datacenter & IRA-energy investor intel",
    "consumer-crowd": "insurance underwriting (consumer risk)",
    "job-postings": "datacenter & energy developer intel",
    "lp-gp-universe": "private-equity LP/GP intelligence",
}


class SyntheticPlaygroundTemplate(ICReportBase):
    """Shareable HTML report for a Nexdata synthetic-data generator run."""

    name = "synthetic_playground"
    display_name = "Synthetic Data Playground Report"
    description = (
        "Shareable, self-contained report for a Nexdata synthetic-data generator "
        "run. Carries a 'Made with Nexdata' CTA — the playground's viral artifact."
    )

    # ── Data gathering ────────────────────────────────────────────────────────

    def gather_data(self, db: Session, params: Dict[str, Any]) -> Dict[str, Any]:
        """Reshape the router-normalized payload for rendering. No DB query —
        the playground passes generator output directly in `params`."""
        generator = params.get("generator", "unknown")
        return {
            "generated_at": datetime.utcnow().isoformat(),
            "generator": generator,
            "generator_label": params.get("generator_label")
            or generator.replace("-", " ").title(),
            "request_params": params.get("request_params") or {},
            "summary": params.get("summary") or {},
            "rows": params.get("rows") or [],
            "chart": params.get("chart"),
            "ref": params.get("ref", ""),
        }

    # ── HTML rendering ────────────────────────────────────────────────────────

    def render_html(self, data: Dict[str, Any]) -> str:
        generator: str = data.get("generator", "unknown")
        generator_label: str = data.get("generator_label", generator)
        summary: Dict[str, Any] = data.get("summary") or {}
        rows: List[Dict[str, Any]] = data.get("rows") or []
        chart: Optional[Dict[str, Any]] = data.get("chart")
        request_params: Dict[str, Any] = data.get("request_params") or {}
        gen_at: str = data.get("generated_at", datetime.utcnow().isoformat())
        ref: str = data.get("ref", "")
        report_title: str = data.get(
            "report_title", f"Synthetic Sample — {generator_label}"
        )
        gen_date = gen_at[:10]

        body = ""
        charts_js = ""

        # ── Header ────────────────────────────────────────────────────────────
        body += page_header(
            title=report_title,
            subtitle=f"Generated by the Nexdata Synthetic Data Playground | {gen_date}",
            badge="Synthetic sample",
        )

        # ── KPI strip from summary ────────────────────────────────────────────
        if summary:
            cards = [
                kpi_card(str(label), str(value))
                for label, value in list(summary.items())[:5]
            ]
            body += kpi_strip(cards)

        # ── Section 1: the generated sample ───────────────────────────────────
        body += section_start(1, f"{generator_label} — Sample Output", "sample")

        if request_params:
            param_str = " · ".join(f"{k}={v}" for k, v in request_params.items())
            body += callout(
                f"<strong>Parameters:</strong> {param_str}", variant="info"
            )
            body += '<div style="margin-top:16px"></div>'

        # Optional chart
        if chart and chart.get("labels") and chart.get("series"):
            labels = chart["labels"]
            series = chart["series"]
            datasets = [
                {
                    "label": s.get("label", f"Series {i + 1}"),
                    "data": s.get("data", []),
                    "color": CHART_COLORS[i % len(CHART_COLORS)],
                    "fill": i == 0 and len(series) == 1,
                }
                for i, s in enumerate(series)
            ]
            line_cfg = build_line_chart_config(
                labels=labels, datasets=datasets, y_label=chart.get("y_label", "")
            )
            # CSS fallback uses the first series, last 8 points
            first = series[0].get("data", []) if series else []
            fb_labels = [str(x) for x in labels[-8:]]
            fb_values = [float(v) if v is not None else 0.0 for v in first[-8:]]
            fallback = build_bar_fallback(fb_labels, fb_values) if fb_values else ""
            body += chart_container(
                chart_id="pg_chart",
                chart_config_json=json.dumps(line_cfg),
                fallback_html=fallback,
                size="medium",
            )
            charts_js += chart_init_js("pg_chart", json.dumps(line_cfg))

        # Sample data table (<=20 rows)
        if rows:
            headers = list(rows[0].keys())
            table_rows = [
                [self._fmt(r.get(h)) for h in headers] for r in rows[:20]
            ]
            body += data_table(headers, table_rows)
            if len(rows) > 20:
                body += (
                    f'<div style="margin-top:8px;font-size:12px;color:var(--gray-500)">'
                    f'Showing 20 of {len(rows):,} generated records.</div>'
                )
        else:
            body += callout(
                "<strong>No tabular sample.</strong> This run produced a "
                "summary-only result.",
                variant="info",
            )

        body += section_end()

        # ── Section 2: the CTA — viral growth mechanism ───────────────────────
        body += section_start(2, "From Sample to Production", "cta")
        body += self._render_cta_block(generator, ref)
        body += section_end()

        # ── Footer ────────────────────────────────────────────────────────────
        body += page_footer(
            notes=[
                "This report contains SYNTHETIC data generated on demand — no real "
                "company, person, or market data is represented.",
                f"Generator: {generator} | Nexdata Synthetic Data Playground.",
                "The full Nexdata platform fuses synthetic generators with 28+ real "
                "public-data sources for production investor/underwriter/operator workflows.",
            ],
            generated_line=(
                f"Generated {gen_at[:19]} UTC | Nexdata Synthetic Data Playground | PLAN_063"
            ),
        )

        return html_document(
            title=f"{report_title} | {gen_date}",
            body_content=body,
            charts_js=charts_js,
        )

    # ── CTA block (C7) ────────────────────────────────────────────────────────

    def _render_cta_block(self, generator: str, ref: str) -> str:
        """The 'Made with Nexdata' CTA. Wrapped in a STABLE anchor —
        `<!-- CTA_BLOCK_PLACEHOLDER -->` + `id="nexdata-cta"` — so Step 6/8 code
        can locate / rewrite it. Links fall back to in-app anchors until
        canonical marketing URLs exist (PLAN_063 open decision #3)."""
        vertical = _VERTICAL_HINT.get(generator, "investor & operator intelligence")
        ref_q = f"&ref={ref}" if ref else ""
        primary_href = f"/playground.html?from=playground&gen={generator}{ref_q}#platform"
        secondary_href = f"/playground.html?from=playground&gen={generator}{ref_q}"
        return f"""<!-- CTA_BLOCK_PLACEHOLDER -->
<div id="nexdata-cta" style="background:var(--gray-50);border:1px solid var(--gray-200);
     border-top:4px solid {BLUE};border-radius:10px;padding:28px 24px;text-align:center">
  <div style="font-size:20px;font-weight:800;color:var(--gray-900);margin-bottom:8px">
    {CTA_HEADLINE}
  </div>
  <div style="font-size:14px;color:var(--gray-600);margin-bottom:6px">{CTA_SUBCOPY}</div>
  <div style="font-size:13px;color:{TEAL};font-weight:600;margin-bottom:20px">
    Most relevant for: {vertical}
  </div>
  <div style="display:flex;gap:12px;justify-content:center;flex-wrap:wrap">
    <a href="{primary_href}"
       style="background:{BLUE};color:#fff;text-decoration:none;font-weight:600;
              padding:12px 28px;border-radius:8px;display:inline-block">
      See the platform
    </a>
    <a href="{secondary_href}"
       style="background:transparent;color:{BLUE};text-decoration:none;font-weight:600;
              padding:12px 28px;border-radius:8px;display:inline-block;
              border:1px solid {BLUE}">
      Run your own
    </a>
  </div>
</div>"""

    # ── Excel rendering (unsupported) ─────────────────────────────────────────

    def render_excel(self, data: Dict[str, Any]) -> bytes:
        """The playground only ever requests HTML. Explicit stub for clarity."""
        raise NotImplementedError(
            "SyntheticPlaygroundTemplate only supports HTML output."
        )

    # ── helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _fmt(value: Any) -> str:
        """Format a cell value for the sample table."""
        if value is None:
            return "—"
        if isinstance(value, float):
            return f"{value:,.2f}" if abs(value) < 1e6 else f"{value:,.0f}"
        if isinstance(value, int):
            return f"{value:,}"
        return str(value)
