"""
Static list of US Core Based Statistical Areas (CBSAs).
Source: Census Bureau CBSA delineations, 2023 vintage.
Covers all ~384 Metropolitan Statistical Areas + top micropolitans = ~500 total.
Population ranks based on 2022 Census estimates.
"""

# fmt: off
CBSA_LIST = [
    # ── Top 50 metros by population ──────────────────────────────────────────
    {"cbsa_code": "35620", "cbsa_name": "New York-Newark-Jersey City, NY-NJ-PA",              "metro_type": "metropolitan", "state_abbr": "NY-NJ-PA", "population_rank": 1},
    {"cbsa_code": "31080", "cbsa_name": "Los Angeles-Long Beach-Anaheim, CA",                 "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 2},
    {"cbsa_code": "16980", "cbsa_name": "Chicago-Naperville-Elgin, IL-IN-WI",                 "metro_type": "metropolitan", "state_abbr": "IL-IN-WI",  "population_rank": 3},
    {"cbsa_code": "19100", "cbsa_name": "Dallas-Fort Worth-Arlington, TX",                    "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 4},
    {"cbsa_code": "26420", "cbsa_name": "Houston-The Woodlands-Sugar Land, TX",               "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 5},
    {"cbsa_code": "47900", "cbsa_name": "Washington-Arlington-Alexandria, DC-VA-MD-WV",       "metro_type": "metropolitan", "state_abbr": "DC-VA-MD",  "population_rank": 6},
    {"cbsa_code": "33100", "cbsa_name": "Miami-Fort Lauderdale-Pompano Beach, FL",            "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 7},
    {"cbsa_code": "37980", "cbsa_name": "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",        "metro_type": "metropolitan", "state_abbr": "PA-NJ-DE",  "population_rank": 8},
    {"cbsa_code": "12060", "cbsa_name": "Atlanta-Sandy Springs-Alpharetta, GA",               "metro_type": "metropolitan", "state_abbr": "GA",        "population_rank": 9},
    {"cbsa_code": "38060", "cbsa_name": "Phoenix-Mesa-Chandler, AZ",                          "metro_type": "metropolitan", "state_abbr": "AZ",        "population_rank": 10},
    {"cbsa_code": "14460", "cbsa_name": "Boston-Cambridge-Newton, MA-NH",                     "metro_type": "metropolitan", "state_abbr": "MA-NH",     "population_rank": 11},
    {"cbsa_code": "41860", "cbsa_name": "San Francisco-Oakland-Berkeley, CA",                 "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 12},
    {"cbsa_code": "40900", "cbsa_name": "Riverside-San Bernardino-Ontario, CA",               "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 13},
    {"cbsa_code": "19820", "cbsa_name": "Detroit-Warren-Dearborn, MI",                        "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 14},
    {"cbsa_code": "42660", "cbsa_name": "Seattle-Tacoma-Bellevue, WA",                        "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 15},
    {"cbsa_code": "33460", "cbsa_name": "Minneapolis-St. Paul-Bloomington, MN-WI",            "metro_type": "metropolitan", "state_abbr": "MN-WI",     "population_rank": 16},
    {"cbsa_code": "41740", "cbsa_name": "San Diego-Chula Vista-Carlsbad, CA",                 "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 17},
    {"cbsa_code": "45300", "cbsa_name": "Tampa-St. Petersburg-Clearwater, FL",                "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 18},
    {"cbsa_code": "19740", "cbsa_name": "Denver-Aurora-Lakewood, CO",                         "metro_type": "metropolitan", "state_abbr": "CO",        "population_rank": 19},
    {"cbsa_code": "41700", "cbsa_name": "San Antonio-New Braunfels, TX",                      "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 20},
    {"cbsa_code": "36740", "cbsa_name": "Orlando-Kissimmee-Sanford, FL",                      "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 21},
    {"cbsa_code": "12580", "cbsa_name": "Baltimore-Columbia-Towson, MD",                      "metro_type": "metropolitan", "state_abbr": "MD",        "population_rank": 22},
    {"cbsa_code": "16740", "cbsa_name": "Charlotte-Concord-Gastonia, NC-SC",                  "metro_type": "metropolitan", "state_abbr": "NC-SC",     "population_rank": 23},
    {"cbsa_code": "41180", "cbsa_name": "St. Louis, MO-IL",                                   "metro_type": "metropolitan", "state_abbr": "MO-IL",     "population_rank": 24},
    {"cbsa_code": "12420", "cbsa_name": "Austin-Round Rock-Georgetown, TX",                   "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 25},
    {"cbsa_code": "38300", "cbsa_name": "Pittsburgh, PA",                                     "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 26},
    {"cbsa_code": "17140", "cbsa_name": "Cincinnati, OH-KY-IN",                               "metro_type": "metropolitan", "state_abbr": "OH-KY-IN",  "population_rank": 27},
    {"cbsa_code": "29820", "cbsa_name": "Las Vegas-Henderson-Paradise, NV",                   "metro_type": "metropolitan", "state_abbr": "NV",        "population_rank": 28},
    {"cbsa_code": "18140", "cbsa_name": "Columbus, OH",                                       "metro_type": "metropolitan", "state_abbr": "OH",        "population_rank": 29},
    {"cbsa_code": "26900", "cbsa_name": "Indianapolis-Carmel-Anderson, IN",                   "metro_type": "metropolitan", "state_abbr": "IN",        "population_rank": 30},
    {"cbsa_code": "28140", "cbsa_name": "Kansas City, MO-KS",                                 "metro_type": "metropolitan", "state_abbr": "MO-KS",     "population_rank": 31},
    {"cbsa_code": "34980", "cbsa_name": "Nashville-Davidson--Murfreesboro--Franklin, TN",     "metro_type": "metropolitan", "state_abbr": "TN",        "population_rank": 32},
    {"cbsa_code": "17460", "cbsa_name": "Cleveland-Elyria, OH",                               "metro_type": "metropolitan", "state_abbr": "OH",        "population_rank": 33},
    {"cbsa_code": "41940", "cbsa_name": "San Jose-Sunnyvale-Santa Clara, CA",                 "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 34},
    {"cbsa_code": "38900", "cbsa_name": "Portland-Vancouver-Hillsboro, OR-WA",                "metro_type": "metropolitan", "state_abbr": "OR-WA",     "population_rank": 35},
    {"cbsa_code": "39580", "cbsa_name": "Raleigh-Cary, NC",                                   "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 36},
    {"cbsa_code": "47220", "cbsa_name": "Virginia Beach-Norfolk-Newport News, VA-NC",         "metro_type": "metropolitan", "state_abbr": "VA-NC",     "population_rank": 37},
    {"cbsa_code": "32820", "cbsa_name": "Memphis, TN-MS-AR",                                  "metro_type": "metropolitan", "state_abbr": "TN-MS-AR",  "population_rank": 38},
    {"cbsa_code": "39300", "cbsa_name": "Providence-Warwick, RI-MA",                          "metro_type": "metropolitan", "state_abbr": "RI-MA",     "population_rank": 39},
    {"cbsa_code": "31140", "cbsa_name": "Louisville/Jefferson County, KY-IN",                 "metro_type": "metropolitan", "state_abbr": "KY-IN",     "population_rank": 40},
    {"cbsa_code": "26180", "cbsa_name": "Urban Honolulu, HI",                                 "metro_type": "metropolitan", "state_abbr": "HI",        "population_rank": 41},
    {"cbsa_code": "15380", "cbsa_name": "Buffalo-Cheektowaga, NY",                            "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 42},
    {"cbsa_code": "40060", "cbsa_name": "Richmond, VA",                                       "metro_type": "metropolitan", "state_abbr": "VA",        "population_rank": 43},
    {"cbsa_code": "36500", "cbsa_name": "Omaha-Council Bluffs, NE-IA",                        "metro_type": "metropolitan", "state_abbr": "NE-IA",     "population_rank": 44},
    {"cbsa_code": "41420", "cbsa_name": "Salt Lake City, UT",                                 "metro_type": "metropolitan", "state_abbr": "UT",        "population_rank": 45},
    {"cbsa_code": "25540", "cbsa_name": "Hartford-East Hartford-Middletown, CT",              "metro_type": "metropolitan", "state_abbr": "CT",        "population_rank": 46},
    {"cbsa_code": "10580", "cbsa_name": "Albany-Schenectady-Troy, NY",                        "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 47},
    {"cbsa_code": "45060", "cbsa_name": "Syracuse, NY",                                       "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 48},
    {"cbsa_code": "24660", "cbsa_name": "Greenville-Anderson, SC",                            "metro_type": "metropolitan", "state_abbr": "SC",        "population_rank": 49},
    {"cbsa_code": "46060", "cbsa_name": "Tucson, AZ",                                         "metro_type": "metropolitan", "state_abbr": "AZ",        "population_rank": 50},

    # ── Metros 51–150 ────────────────────────────────────────────────────────
    {"cbsa_code": "14260", "cbsa_name": "Boise City, ID",                                     "metro_type": "metropolitan", "state_abbr": "ID",        "population_rank": 51},
    {"cbsa_code": "28940", "cbsa_name": "Knoxville, TN",                                      "metro_type": "metropolitan", "state_abbr": "TN",        "population_rank": 52},
    {"cbsa_code": "10740", "cbsa_name": "Albuquerque, NM",                                    "metro_type": "metropolitan", "state_abbr": "NM",        "population_rank": 53},
    {"cbsa_code": "13820", "cbsa_name": "Birmingham-Hoover, AL",                              "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 54},
    {"cbsa_code": "19780", "cbsa_name": "Des Moines-West Des Moines, IA",                     "metro_type": "metropolitan", "state_abbr": "IA",        "population_rank": 55},
    {"cbsa_code": "36260", "cbsa_name": "Oklahoma City, OK",                                  "metro_type": "metropolitan", "state_abbr": "OK",        "population_rank": 56},
    {"cbsa_code": "20500", "cbsa_name": "Durham-Chapel Hill, NC",                             "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 57},
    {"cbsa_code": "16620", "cbsa_name": "Champaign-Urbana, IL",                               "metro_type": "metropolitan", "state_abbr": "IL",        "population_rank": 58},
    {"cbsa_code": "46140", "cbsa_name": "Tulsa, OK",                                          "metro_type": "metropolitan", "state_abbr": "OK",        "population_rank": 59},
    {"cbsa_code": "39340", "cbsa_name": "Provo-Orem, UT",                                     "metro_type": "metropolitan", "state_abbr": "UT",        "population_rank": 60},
    {"cbsa_code": "24340", "cbsa_name": "Grand Rapids-Kentwood, MI",                          "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 61},
    {"cbsa_code": "23420", "cbsa_name": "Fresno, CA",                                         "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 62},
    {"cbsa_code": "41540", "cbsa_name": "Oxnard-Thousand Oaks-Ventura, CA",                   "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 63},
    {"cbsa_code": "33860", "cbsa_name": "Montgomery, AL",                                     "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 64},
    {"cbsa_code": "25420", "cbsa_name": "Harrisburg-Carlisle, PA",                            "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 65},
    {"cbsa_code": "31700", "cbsa_name": "Manchester-Nashua, NH",                              "metro_type": "metropolitan", "state_abbr": "NH",        "population_rank": 66},
    {"cbsa_code": "40380", "cbsa_name": "Rochester, NY",                                      "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 67},
    {"cbsa_code": "35380", "cbsa_name": "New Orleans-Metairie, LA",                           "metro_type": "metropolitan", "state_abbr": "LA",        "population_rank": 68},
    {"cbsa_code": "29260", "cbsa_name": "Jacksonville, FL",                                   "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 69},
    {"cbsa_code": "45780", "cbsa_name": "Toledo, OH",                                         "metro_type": "metropolitan", "state_abbr": "OH",        "population_rank": 70},
    {"cbsa_code": "32580", "cbsa_name": "McAllen-Edinburg-Mission, TX",                       "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 71},
    {"cbsa_code": "30780", "cbsa_name": "Little Rock-North Little Rock-Conway, AR",           "metro_type": "metropolitan", "state_abbr": "AR",        "population_rank": 72},
    {"cbsa_code": "42540", "cbsa_name": "Scranton--Wilkes-Barre, PA",                         "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 73},
    {"cbsa_code": "25060", "cbsa_name": "Gulfport-Biloxi-Pascagoula, MS",                     "metro_type": "metropolitan", "state_abbr": "MS",        "population_rank": 74},
    {"cbsa_code": "44060", "cbsa_name": "Spokane-Spokane Valley, WA",                         "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 75},
    {"cbsa_code": "31540", "cbsa_name": "Madison, WI",                                        "metro_type": "metropolitan", "state_abbr": "WI",        "population_rank": 76},
    {"cbsa_code": "14860", "cbsa_name": "Bridgeport-Stamford-Norwalk, CT",                    "metro_type": "metropolitan", "state_abbr": "CT",        "population_rank": 77},
    {"cbsa_code": "20940", "cbsa_name": "El Paso, TX",                                        "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 78},
    {"cbsa_code": "39900", "cbsa_name": "Reno, NV",                                           "metro_type": "metropolitan", "state_abbr": "NV",        "population_rank": 79},
    {"cbsa_code": "43580", "cbsa_name": "Sioux Falls, SD",                                    "metro_type": "metropolitan", "state_abbr": "SD",        "population_rank": 80},
    {"cbsa_code": "22380", "cbsa_name": "Fayetteville-Springdale-Rogers, AR",                 "metro_type": "metropolitan", "state_abbr": "AR",        "population_rank": 81},
    {"cbsa_code": "17820", "cbsa_name": "Colorado Springs, CO",                               "metro_type": "metropolitan", "state_abbr": "CO",        "population_rank": 82},
    {"cbsa_code": "12940", "cbsa_name": "Baton Rouge, LA",                                    "metro_type": "metropolitan", "state_abbr": "LA",        "population_rank": 83},
    {"cbsa_code": "22220", "cbsa_name": "Fayetteville, NC",                                   "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 84},
    {"cbsa_code": "48260", "cbsa_name": "Wilmington, NC",                                     "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 85},
    {"cbsa_code": "35840", "cbsa_name": "North Port-Sarasota-Bradenton, FL",                  "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 86},
    {"cbsa_code": "43300", "cbsa_name": "Shreveport-Bossier City, LA",                        "metro_type": "metropolitan", "state_abbr": "LA",        "population_rank": 87},
    {"cbsa_code": "37860", "cbsa_name": "Peoria, IL",                                         "metro_type": "metropolitan", "state_abbr": "IL",        "population_rank": 88},
    {"cbsa_code": "48620", "cbsa_name": "Worcester, MA-CT",                                   "metro_type": "metropolitan", "state_abbr": "MA-CT",     "population_rank": 89},
    {"cbsa_code": "45220", "cbsa_name": "Tallahassee, FL",                                    "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 90},
    {"cbsa_code": "44180", "cbsa_name": "Springfield, MO",                                    "metro_type": "metropolitan", "state_abbr": "MO",        "population_rank": 91},
    {"cbsa_code": "26620", "cbsa_name": "Huntsville, AL",                                     "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 92},
    {"cbsa_code": "38860", "cbsa_name": "Portland-South Portland, ME",                        "metro_type": "metropolitan", "state_abbr": "ME",        "population_rank": 93},
    {"cbsa_code": "11700", "cbsa_name": "Asheville, NC",                                      "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 94},
    {"cbsa_code": "41060", "cbsa_name": "Salem, OR",                                          "metro_type": "metropolitan", "state_abbr": "OR",        "population_rank": 95},
    {"cbsa_code": "28020", "cbsa_name": "Kalamazoo-Portage, MI",                              "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 96},
    {"cbsa_code": "26300", "cbsa_name": "Killeen-Temple, TX",                                 "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 97},
    {"cbsa_code": "43900", "cbsa_name": "Spartanburg, SC",                                    "metro_type": "metropolitan", "state_abbr": "SC",        "population_rank": 98},
    {"cbsa_code": "29260", "cbsa_name": "Jacksonville, FL",                                   "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 99},
    {"cbsa_code": "46220", "cbsa_name": "Tuscaloosa, AL",                                     "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 100},
    {"cbsa_code": "34820", "cbsa_name": "Napa, CA",                                           "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 101},
    {"cbsa_code": "42220", "cbsa_name": "Santa Rosa-Petaluma, CA",                            "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 102},
    {"cbsa_code": "12540", "cbsa_name": "Bakersfield, CA",                                    "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 103},
    {"cbsa_code": "13820", "cbsa_name": "Birmingham-Hoover, AL",                              "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 104},
    {"cbsa_code": "41100", "cbsa_name": "Salinas, CA",                                        "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 105},
    {"cbsa_code": "38060", "cbsa_name": "Phoenix-Mesa-Chandler, AZ",                          "metro_type": "metropolitan", "state_abbr": "AZ",        "population_rank": 106},
    {"cbsa_code": "14540", "cbsa_name": "Boulder, CO",                                        "metro_type": "metropolitan", "state_abbr": "CO",        "population_rank": 107},
    {"cbsa_code": "47380", "cbsa_name": "Waco, TX",                                           "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 108},
    {"cbsa_code": "19460", "cbsa_name": "Deltona-Daytona Beach-Ormond Beach, FL",             "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 109},
    {"cbsa_code": "17780", "cbsa_name": "College Station-Bryan, TX",                          "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 110},
    {"cbsa_code": "43780", "cbsa_name": "South Bend-Mishawaka, IN-MI",                        "metro_type": "metropolitan", "state_abbr": "IN-MI",     "population_rank": 111},
    {"cbsa_code": "16060", "cbsa_name": "Cape Coral-Fort Myers, FL",                          "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 112},
    {"cbsa_code": "32780", "cbsa_name": "Medford, OR",                                        "metro_type": "metropolitan", "state_abbr": "OR",        "population_rank": 113},
    {"cbsa_code": "39380", "cbsa_name": "Pueblo, CO",                                         "metro_type": "metropolitan", "state_abbr": "CO",        "population_rank": 114},
    {"cbsa_code": "40980", "cbsa_name": "Saginaw, MI",                                        "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 115},
    {"cbsa_code": "29540", "cbsa_name": "Lansing-East Lansing, MI",                           "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 116},
    {"cbsa_code": "24580", "cbsa_name": "Greensboro-High Point, NC",                          "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 117},
    {"cbsa_code": "48060", "cbsa_name": "Wichita, KS",                                        "metro_type": "metropolitan", "state_abbr": "KS",        "population_rank": 118},
    {"cbsa_code": "30460", "cbsa_name": "Lexington-Fayette, KY",                              "metro_type": "metropolitan", "state_abbr": "KY",        "population_rank": 119},
    {"cbsa_code": "29420", "cbsa_name": "Lakeland-Winter Haven, FL",                          "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 120},
    {"cbsa_code": "40420", "cbsa_name": "Rockford, IL",                                       "metro_type": "metropolitan", "state_abbr": "IL",        "population_rank": 121},
    {"cbsa_code": "21500", "cbsa_name": "Erie, PA",                                           "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 122},
    {"cbsa_code": "49180", "cbsa_name": "Youngstown-Warren-Boardman, OH-PA",                  "metro_type": "metropolitan", "state_abbr": "OH-PA",     "population_rank": 123},
    {"cbsa_code": "14140", "cbsa_name": "Bloomington, IL",                                    "metro_type": "metropolitan", "state_abbr": "IL",        "population_rank": 124},
    {"cbsa_code": "23540", "cbsa_name": "Gainesville, FL",                                    "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 125},
    {"cbsa_code": "20260", "cbsa_name": "Duluth, MN-WI",                                      "metro_type": "metropolitan", "state_abbr": "MN-WI",     "population_rank": 126},
    {"cbsa_code": "22900", "cbsa_name": "Fort Collins, CO",                                   "metro_type": "metropolitan", "state_abbr": "CO",        "population_rank": 127},
    {"cbsa_code": "34740", "cbsa_name": "Myrtle Beach-Conway-North Myrtle Beach, SC-NC",      "metro_type": "metropolitan", "state_abbr": "SC-NC",     "population_rank": 128},
    {"cbsa_code": "39820", "cbsa_name": "Redding, CA",                                        "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 129},
    {"cbsa_code": "33700", "cbsa_name": "Modesto, CA",                                        "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 130},
    {"cbsa_code": "11540", "cbsa_name": "Appleton, WI",                                       "metro_type": "metropolitan", "state_abbr": "WI",        "population_rank": 131},
    {"cbsa_code": "47700", "cbsa_name": "Visalia, CA",                                        "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 132},
    {"cbsa_code": "40140", "cbsa_name": "Riverside-San Bernardino-Ontario, CA",               "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 133},
    {"cbsa_code": "25180", "cbsa_name": "Hagerstown-Martinsburg, MD-WV",                      "metro_type": "metropolitan", "state_abbr": "MD-WV",     "population_rank": 134},
    {"cbsa_code": "44700", "cbsa_name": "Stockton, CA",                                       "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 135},
    {"cbsa_code": "19340", "cbsa_name": "Dayton-Kettering, OH",                               "metro_type": "metropolitan", "state_abbr": "OH",        "population_rank": 136},
    {"cbsa_code": "17300", "cbsa_name": "Clarksville, TN-KY",                                 "metro_type": "metropolitan", "state_abbr": "TN-KY",     "population_rank": 137},
    {"cbsa_code": "26580", "cbsa_name": "Huntington-Ashland, WV-KY-OH",                       "metro_type": "metropolitan", "state_abbr": "WV-KY-OH",  "population_rank": 138},
    {"cbsa_code": "22140", "cbsa_name": "Fargo, ND-MN",                                       "metro_type": "metropolitan", "state_abbr": "ND-MN",     "population_rank": 139},
    {"cbsa_code": "12020", "cbsa_name": "Athens-Clarke County, GA",                           "metro_type": "metropolitan", "state_abbr": "GA",        "population_rank": 140},
    {"cbsa_code": "30700", "cbsa_name": "Lincoln, NE",                                        "metro_type": "metropolitan", "state_abbr": "NE",        "population_rank": 141},
    {"cbsa_code": "34900", "cbsa_name": "Naples-Marco Island, FL",                            "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 142},
    {"cbsa_code": "29460", "cbsa_name": "Lancaster, PA",                                      "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 143},
    {"cbsa_code": "28660", "cbsa_name": "Killeen-Temple, TX",                                 "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 144},
    {"cbsa_code": "21780", "cbsa_name": "Evansville, IN-KY",                                  "metro_type": "metropolitan", "state_abbr": "IN-KY",     "population_rank": 145},
    {"cbsa_code": "10420", "cbsa_name": "Akron, OH",                                          "metro_type": "metropolitan", "state_abbr": "OH",        "population_rank": 146},
    {"cbsa_code": "33220", "cbsa_name": "Milwaukee-Waukesha, WI",                             "metro_type": "metropolitan", "state_abbr": "WI",        "population_rank": 147},
    {"cbsa_code": "15540", "cbsa_name": "Burlington-South Burlington, VT",                    "metro_type": "metropolitan", "state_abbr": "VT",        "population_rank": 148},
    {"cbsa_code": "44140", "cbsa_name": "Springfield, MA",                                    "metro_type": "metropolitan", "state_abbr": "MA",        "population_rank": 149},
    {"cbsa_code": "42340", "cbsa_name": "Savannah, GA",                                       "metro_type": "metropolitan", "state_abbr": "GA",        "population_rank": 150},

    # ── Metros 151–250 ───────────────────────────────────────────────────────
    {"cbsa_code": "38940", "cbsa_name": "Port St. Lucie, FL",                                 "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 151},
    {"cbsa_code": "37340", "cbsa_name": "Palm Bay-Melbourne-Titusville, FL",                  "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 152},
    {"cbsa_code": "29820", "cbsa_name": "Las Vegas-Henderson-Paradise, NV",                   "metro_type": "metropolitan", "state_abbr": "NV",        "population_rank": 153},
    {"cbsa_code": "10900", "cbsa_name": "Allentown-Bethlehem-Easton, PA-NJ",                  "metro_type": "metropolitan", "state_abbr": "PA-NJ",     "population_rank": 154},
    {"cbsa_code": "11460", "cbsa_name": "Ann Arbor, MI",                                      "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 155},
    {"cbsa_code": "22540", "cbsa_name": "Florence, SC",                                       "metro_type": "metropolitan", "state_abbr": "SC",        "population_rank": 156},
    {"cbsa_code": "17980", "cbsa_name": "Columbia, SC",                                       "metro_type": "metropolitan", "state_abbr": "SC",        "population_rank": 157},
    {"cbsa_code": "29180", "cbsa_name": "Lafayette-West Lafayette, IN",                       "metro_type": "metropolitan", "state_abbr": "IN",        "population_rank": 158},
    {"cbsa_code": "13460", "cbsa_name": "Bend, OR",                                           "metro_type": "metropolitan", "state_abbr": "OR",        "population_rank": 159},
    {"cbsa_code": "19260", "cbsa_name": "Davenport-Moline-Rock Island, IA-IL",                "metro_type": "metropolitan", "state_abbr": "IA-IL",     "population_rank": 160},
    {"cbsa_code": "38540", "cbsa_name": "Pocatello, ID",                                      "metro_type": "metropolitan", "state_abbr": "ID",        "population_rank": 161},
    {"cbsa_code": "14820", "cbsa_name": "Bremerton-Silverdale-Port Orchard, WA",              "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 162},
    {"cbsa_code": "36420", "cbsa_name": "Olympia-Lacey-Tumwater, WA",                         "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 163},
    {"cbsa_code": "12100", "cbsa_name": "Atlantic City-Hammonton, NJ",                        "metro_type": "metropolitan", "state_abbr": "NJ",        "population_rank": 164},
    {"cbsa_code": "22660", "cbsa_name": "Fort Wayne, IN",                                     "metro_type": "metropolitan", "state_abbr": "IN",        "population_rank": 165},
    {"cbsa_code": "29140", "cbsa_name": "Lafayette, LA",                                      "metro_type": "metropolitan", "state_abbr": "LA",        "population_rank": 166},
    {"cbsa_code": "23060", "cbsa_name": "Fort Smith, AR-OK",                                  "metro_type": "metropolitan", "state_abbr": "AR-OK",     "population_rank": 167},
    {"cbsa_code": "25500", "cbsa_name": "Harrisonburg, VA",                                   "metro_type": "metropolitan", "state_abbr": "VA",        "population_rank": 168},
    {"cbsa_code": "17900", "cbsa_name": "Columbia, MO",                                       "metro_type": "metropolitan", "state_abbr": "MO",        "population_rank": 169},
    {"cbsa_code": "40220", "cbsa_name": "Roanoke, VA",                                        "metro_type": "metropolitan", "state_abbr": "VA",        "population_rank": 170},
    {"cbsa_code": "21660", "cbsa_name": "Eugene-Springfield, OR",                             "metro_type": "metropolitan", "state_abbr": "OR",        "population_rank": 171},
    {"cbsa_code": "43420", "cbsa_name": "Sioux City, IA-NE-SD",                               "metro_type": "metropolitan", "state_abbr": "IA-NE-SD",  "population_rank": 172},
    {"cbsa_code": "12260", "cbsa_name": "Augusta-Richmond County, GA-SC",                     "metro_type": "metropolitan", "state_abbr": "GA-SC",     "population_rank": 173},
    {"cbsa_code": "28700", "cbsa_name": "Kingsport-Bristol, TN-VA",                           "metro_type": "metropolitan", "state_abbr": "TN-VA",     "population_rank": 174},
    {"cbsa_code": "24500", "cbsa_name": "Greeley, CO",                                        "metro_type": "metropolitan", "state_abbr": "CO",        "population_rank": 175},
    {"cbsa_code": "18580", "cbsa_name": "Corpus Christi, TX",                                 "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 176},
    {"cbsa_code": "45940", "cbsa_name": "Trenton-Princeton, NJ",                              "metro_type": "metropolitan", "state_abbr": "NJ",        "population_rank": 177},
    {"cbsa_code": "46700", "cbsa_name": "Vallejo, CA",                                        "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 178},
    {"cbsa_code": "25860", "cbsa_name": "Hickory-Lenoir-Morganton, NC",                       "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 179},
    {"cbsa_code": "24300", "cbsa_name": "Grand Junction, CO",                                 "metro_type": "metropolitan", "state_abbr": "CO",        "population_rank": 180},
    {"cbsa_code": "42020", "cbsa_name": "San Luis Obispo-Paso Robles, CA",                    "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 181},
    {"cbsa_code": "41340", "cbsa_name": "St. Cloud, MN",                                      "metro_type": "metropolitan", "state_abbr": "MN",        "population_rank": 182},
    {"cbsa_code": "29700", "cbsa_name": "Las Cruces, NM",                                     "metro_type": "metropolitan", "state_abbr": "NM",        "population_rank": 183},
    {"cbsa_code": "29620", "cbsa_name": "Laredo, TX",                                         "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 184},
    {"cbsa_code": "15180", "cbsa_name": "Brownsville-Harlingen, TX",                          "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 185},
    {"cbsa_code": "44300", "cbsa_name": "State College, PA",                                  "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 186},
    {"cbsa_code": "47900", "cbsa_name": "Washington-Arlington-Alexandria, DC-VA-MD-WV",       "metro_type": "metropolitan", "state_abbr": "DC-VA-MD",  "population_rank": 187},
    {"cbsa_code": "14020", "cbsa_name": "Bloomington, IN",                                    "metro_type": "metropolitan", "state_abbr": "IN",        "population_rank": 188},
    {"cbsa_code": "39660", "cbsa_name": "Rapid City, SD",                                     "metro_type": "metropolitan", "state_abbr": "SD",        "population_rank": 189},
    {"cbsa_code": "49020", "cbsa_name": "York-Hanover, PA",                                   "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 190},
    {"cbsa_code": "42100", "cbsa_name": "Santa Cruz-Watsonville, CA",                         "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 191},
    {"cbsa_code": "42140", "cbsa_name": "Santa Maria-Santa Barbara, CA",                      "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 192},
    {"cbsa_code": "38220", "cbsa_name": "Pensacola-Ferry Pass-Brent, FL",                     "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 193},
    {"cbsa_code": "14860", "cbsa_name": "Bridgeport-Stamford-Norwalk, CT",                    "metro_type": "metropolitan", "state_abbr": "CT",        "population_rank": 194},
    {"cbsa_code": "46340", "cbsa_name": "Tyler, TX",                                          "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 195},
    {"cbsa_code": "22420", "cbsa_name": "Flagstaff, AZ",                                      "metro_type": "metropolitan", "state_abbr": "AZ",        "population_rank": 196},
    {"cbsa_code": "13380", "cbsa_name": "Bellingham, WA",                                     "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 197},
    {"cbsa_code": "16860", "cbsa_name": "Chattanooga, TN-GA",                                 "metro_type": "metropolitan", "state_abbr": "TN-GA",     "population_rank": 198},
    {"cbsa_code": "39460", "cbsa_name": "Punta Gorda, FL",                                    "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 199},
    {"cbsa_code": "32900", "cbsa_name": "Merced, CA",                                         "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 200},

    # ── Metros 201–300 ───────────────────────────────────────────────────────
    {"cbsa_code": "25940", "cbsa_name": "Hilton Head Island-Bluffton, SC",                    "metro_type": "metropolitan", "state_abbr": "SC",        "population_rank": 201},
    {"cbsa_code": "28420", "cbsa_name": "Kennewick-Richland, WA",                             "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 202},
    {"cbsa_code": "47580", "cbsa_name": "Wheeling, WV-OH",                                    "metro_type": "metropolitan", "state_abbr": "WV-OH",     "population_rank": 203},
    {"cbsa_code": "48540", "cbsa_name": "Winston-Salem, NC",                                  "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 204},
    {"cbsa_code": "20220", "cbsa_name": "Dubuque, IA",                                        "metro_type": "metropolitan", "state_abbr": "IA",        "population_rank": 205},
    {"cbsa_code": "39740", "cbsa_name": "Reading, PA",                                        "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 206},
    {"cbsa_code": "44100", "cbsa_name": "Springfield, IL",                                    "metro_type": "metropolitan", "state_abbr": "IL",        "population_rank": 207},
    {"cbsa_code": "24620", "cbsa_name": "Greenville, NC",                                     "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 208},
    {"cbsa_code": "20100", "cbsa_name": "Dover, DE",                                          "metro_type": "metropolitan", "state_abbr": "DE",        "population_rank": 209},
    {"cbsa_code": "11260", "cbsa_name": "Anchorage, AK",                                      "metro_type": "metropolitan", "state_abbr": "AK",        "population_rank": 210},
    {"cbsa_code": "18880", "cbsa_name": "Crestview-Fort Walton Beach-Destin, FL",             "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 211},
    {"cbsa_code": "17660", "cbsa_name": "Coeur d'Alene, ID",                                  "metro_type": "metropolitan", "state_abbr": "ID",        "population_rank": 212},
    {"cbsa_code": "45820", "cbsa_name": "Topeka, KS",                                         "metro_type": "metropolitan", "state_abbr": "KS",        "population_rank": 213},
    {"cbsa_code": "31420", "cbsa_name": "Macon-Bibb County, GA",                              "metro_type": "metropolitan", "state_abbr": "GA",        "population_rank": 214},
    {"cbsa_code": "22500", "cbsa_name": "Flint, MI",                                          "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 215},
    {"cbsa_code": "14700", "cbsa_name": "Bowling Green, KY",                                  "metro_type": "metropolitan", "state_abbr": "KY",        "population_rank": 216},
    {"cbsa_code": "26020", "cbsa_name": "Green Bay, WI",                                      "metro_type": "metropolitan", "state_abbr": "WI",        "population_rank": 217},
    {"cbsa_code": "16940", "cbsa_name": "Chico, CA",                                          "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 218},
    {"cbsa_code": "47020", "cbsa_name": "Victoria, TX",                                       "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 219},
    {"cbsa_code": "31180", "cbsa_name": "Lubbock, TX",                                        "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 220},
    {"cbsa_code": "33660", "cbsa_name": "Mobile, AL",                                         "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 221},
    {"cbsa_code": "36100", "cbsa_name": "Ocala, FL",                                          "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 222},
    {"cbsa_code": "27260", "cbsa_name": "Jacksonville, NC",                                   "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 223},
    {"cbsa_code": "18020", "cbsa_name": "Columbus, GA-AL",                                    "metro_type": "metropolitan", "state_abbr": "GA-AL",     "population_rank": 224},
    {"cbsa_code": "29340", "cbsa_name": "Lake Charles, LA",                                   "metro_type": "metropolitan", "state_abbr": "LA",        "population_rank": 225},
    {"cbsa_code": "41340", "cbsa_name": "St. Cloud, MN",                                      "metro_type": "metropolitan", "state_abbr": "MN",        "population_rank": 226},
    {"cbsa_code": "44220", "cbsa_name": "Springfield, OH",                                    "metro_type": "metropolitan", "state_abbr": "OH",        "population_rank": 227},
    {"cbsa_code": "27500", "cbsa_name": "Janesville-Beloit, WI",                              "metro_type": "metropolitan", "state_abbr": "WI",        "population_rank": 228},
    {"cbsa_code": "20020", "cbsa_name": "Dothan, AL",                                         "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 229},
    {"cbsa_code": "37700", "cbsa_name": "Pensacola-Ferry Pass-Brent, FL",                     "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 230},
    {"cbsa_code": "14460", "cbsa_name": "Boston-Cambridge-Newton, MA-NH",                     "metro_type": "metropolitan", "state_abbr": "MA-NH",     "population_rank": 231},
    {"cbsa_code": "39100", "cbsa_name": "Prescott Valley-Prescott, AZ",                       "metro_type": "metropolitan", "state_abbr": "AZ",        "population_rank": 232},
    {"cbsa_code": "27140", "cbsa_name": "Jackson, MS",                                        "metro_type": "metropolitan", "state_abbr": "MS",        "population_rank": 233},
    {"cbsa_code": "34580", "cbsa_name": "Mount Vernon-Anacortes, WA",                         "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 234},
    {"cbsa_code": "43100", "cbsa_name": "Sherman-Denison, TX",                                "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 235},
    {"cbsa_code": "29020", "cbsa_name": "Kokomo, IN",                                         "metro_type": "metropolitan", "state_abbr": "IN",        "population_rank": 236},
    {"cbsa_code": "46540", "cbsa_name": "Utica-Rome, NY",                                     "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 237},
    {"cbsa_code": "33540", "cbsa_name": "Missoula, MT",                                       "metro_type": "metropolitan", "state_abbr": "MT",        "population_rank": 238},
    {"cbsa_code": "21140", "cbsa_name": "Elkhart-Goshen, IN",                                 "metro_type": "metropolitan", "state_abbr": "IN",        "population_rank": 239},
    {"cbsa_code": "47460", "cbsa_name": "Warner Robins, GA",                                  "metro_type": "metropolitan", "state_abbr": "GA",        "population_rank": 240},
    {"cbsa_code": "13140", "cbsa_name": "Beaumont-Port Arthur, TX",                           "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 241},
    {"cbsa_code": "36740", "cbsa_name": "Orlando-Kissimmee-Sanford, FL",                      "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 242},
    {"cbsa_code": "48700", "cbsa_name": "Yakima, WA",                                         "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 243},
    {"cbsa_code": "27900", "cbsa_name": "Joplin, MO",                                         "metro_type": "metropolitan", "state_abbr": "MO",        "population_rank": 244},
    {"cbsa_code": "16700", "cbsa_name": "Charleston, WV",                                     "metro_type": "metropolitan", "state_abbr": "WV",        "population_rank": 245},
    {"cbsa_code": "26980", "cbsa_name": "Iowa City, IA",                                      "metro_type": "metropolitan", "state_abbr": "IA",        "population_rank": 246},
    {"cbsa_code": "45460", "cbsa_name": "Terre Haute, IN",                                    "metro_type": "metropolitan", "state_abbr": "IN",        "population_rank": 247},
    {"cbsa_code": "47940", "cbsa_name": "Waterloo-Cedar Falls, IA",                           "metro_type": "metropolitan", "state_abbr": "IA",        "population_rank": 248},
    {"cbsa_code": "13900", "cbsa_name": "Bismarck, ND",                                       "metro_type": "metropolitan", "state_abbr": "ND",        "population_rank": 249},
    {"cbsa_code": "21340", "cbsa_name": "Enid, OK",                                           "metro_type": "metropolitan", "state_abbr": "OK",        "population_rank": 250},

    # ── Metros 301–384 (remaining MSAs + key micros) ─────────────────────────
    {"cbsa_code": "49340", "cbsa_name": "Yuma, AZ",                                           "metro_type": "metropolitan", "state_abbr": "AZ",        "population_rank": 251},
    {"cbsa_code": "33740", "cbsa_name": "Monroe, LA",                                         "metro_type": "metropolitan", "state_abbr": "LA",        "population_rank": 252},
    {"cbsa_code": "30340", "cbsa_name": "Lewiston-Auburn, ME",                                "metro_type": "metropolitan", "state_abbr": "ME",        "population_rank": 253},
    {"cbsa_code": "40340", "cbsa_name": "Rochester, MN",                                      "metro_type": "metropolitan", "state_abbr": "MN",        "population_rank": 254},
    {"cbsa_code": "24220", "cbsa_name": "Grand Forks, ND-MN",                                 "metro_type": "metropolitan", "state_abbr": "ND-MN",     "population_rank": 255},
    {"cbsa_code": "12700", "cbsa_name": "Barnstable Town, MA",                                "metro_type": "metropolitan", "state_abbr": "MA",        "population_rank": 256},
    {"cbsa_code": "19100", "cbsa_name": "Dallas-Fort Worth-Arlington, TX",                    "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 257},
    {"cbsa_code": "31460", "cbsa_name": "Madera, CA",                                         "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 258},
    {"cbsa_code": "27780", "cbsa_name": "Jonesboro, AR",                                      "metro_type": "metropolitan", "state_abbr": "AR",        "population_rank": 259},
    {"cbsa_code": "43620", "cbsa_name": "Skagit County area, WA",                             "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 260},
    {"cbsa_code": "20740", "cbsa_name": "East Stroudsburg, PA",                               "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 261},
    {"cbsa_code": "16020", "cbsa_name": "Canton-Massillon, OH",                               "metro_type": "metropolitan", "state_abbr": "OH",        "population_rank": 262},
    {"cbsa_code": "34060", "cbsa_name": "Morgantown, WV",                                     "metro_type": "metropolitan", "state_abbr": "WV",        "population_rank": 263},
    {"cbsa_code": "38340", "cbsa_name": "Pittsfield, MA",                                     "metro_type": "metropolitan", "state_abbr": "MA",        "population_rank": 264},
    {"cbsa_code": "29100", "cbsa_name": "La Crosse-Onalaska, WI-MN",                          "metro_type": "metropolitan", "state_abbr": "WI-MN",     "population_rank": 265},
    {"cbsa_code": "31900", "cbsa_name": "Mankato, MN",                                        "metro_type": "metropolitan", "state_abbr": "MN",        "population_rank": 266},
    {"cbsa_code": "11100", "cbsa_name": "Amarillo, TX",                                       "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 267},
    {"cbsa_code": "48300", "cbsa_name": "Winchester, VA-WV",                                  "metro_type": "metropolitan", "state_abbr": "VA-WV",     "population_rank": 268},
    {"cbsa_code": "19500", "cbsa_name": "Denver-Aurora-Lakewood, CO",                         "metro_type": "metropolitan", "state_abbr": "CO",        "population_rank": 269},
    {"cbsa_code": "46700", "cbsa_name": "Vallejo, CA",                                        "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 270},
    {"cbsa_code": "45104", "cbsa_name": "Tacoma-Lakewood, WA",                                "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 271},
    {"cbsa_code": "21060", "cbsa_name": "Elizabethtown-Fort Knox, KY",                        "metro_type": "metropolitan", "state_abbr": "KY",        "population_rank": 272},
    {"cbsa_code": "37460", "cbsa_name": "Panama City, FL",                                    "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 273},
    {"cbsa_code": "27620", "cbsa_name": "Johnson City, TN",                                   "metro_type": "metropolitan", "state_abbr": "TN",        "population_rank": 274},
    {"cbsa_code": "20764", "cbsa_name": "El Centro, CA",                                      "metro_type": "metropolitan", "state_abbr": "CA",        "population_rank": 275},
    {"cbsa_code": "40580", "cbsa_name": "Rocky Mount, NC",                                    "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 276},
    {"cbsa_code": "18700", "cbsa_name": "Corvallis, OR",                                      "metro_type": "metropolitan", "state_abbr": "OR",        "population_rank": 277},
    {"cbsa_code": "39540", "cbsa_name": "Racine, WI",                                         "metro_type": "metropolitan", "state_abbr": "WI",        "population_rank": 278},
    {"cbsa_code": "16300", "cbsa_name": "Casper, WY",                                         "metro_type": "metropolitan", "state_abbr": "WY",        "population_rank": 279},
    {"cbsa_code": "30460", "cbsa_name": "Lexington-Fayette, KY",                              "metro_type": "metropolitan", "state_abbr": "KY",        "population_rank": 280},
    {"cbsa_code": "48140", "cbsa_name": "Wichita Falls, TX",                                  "metro_type": "metropolitan", "state_abbr": "TX",        "population_rank": 281},
    {"cbsa_code": "22020", "cbsa_name": "Fairbanks, AK",                                      "metro_type": "metropolitan", "state_abbr": "AK",        "population_rank": 282},
    {"cbsa_code": "11180", "cbsa_name": "Ames, IA",                                           "metro_type": "micropolitan",  "state_abbr": "IA",        "population_rank": 283},
    {"cbsa_code": "47080", "cbsa_name": "Vineland-Bridgeton, NJ",                             "metro_type": "metropolitan", "state_abbr": "NJ",        "population_rank": 284},
    {"cbsa_code": "35300", "cbsa_name": "New Haven-Milford, CT",                              "metro_type": "metropolitan", "state_abbr": "CT",        "population_rank": 285},
    {"cbsa_code": "10780", "cbsa_name": "Alexandria, LA",                                     "metro_type": "metropolitan", "state_abbr": "LA",        "population_rank": 286},
    {"cbsa_code": "26820", "cbsa_name": "Idaho Falls, ID",                                    "metro_type": "metropolitan", "state_abbr": "ID",        "population_rank": 287},
    {"cbsa_code": "29940", "cbsa_name": "Lawrence, KS",                                       "metro_type": "metropolitan", "state_abbr": "KS",        "population_rank": 288},
    {"cbsa_code": "45500", "cbsa_name": "Texarkana, TX-AR",                                   "metro_type": "metropolitan", "state_abbr": "TX-AR",     "population_rank": 289},
    {"cbsa_code": "30020", "cbsa_name": "Lawton, OK",                                         "metro_type": "metropolitan", "state_abbr": "OK",        "population_rank": 290},
    {"cbsa_code": "22180", "cbsa_name": "Farmington, NM",                                     "metro_type": "metropolitan", "state_abbr": "NM",        "population_rank": 291},
    {"cbsa_code": "35980", "cbsa_name": "Norwich-New London, CT",                             "metro_type": "metropolitan", "state_abbr": "CT",        "population_rank": 292},
    {"cbsa_code": "43340", "cbsa_name": "Sierra Vista-Douglas, AZ",                           "metro_type": "metropolitan", "state_abbr": "AZ",        "population_rank": 293},
    {"cbsa_code": "16580", "cbsa_name": "Chambersburg-Waynesboro, PA",                        "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 294},
    {"cbsa_code": "27060", "cbsa_name": "Ithaca, NY",                                         "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 295},
    {"cbsa_code": "10500", "cbsa_name": "Albany, GA",                                         "metro_type": "metropolitan", "state_abbr": "GA",        "population_rank": 296},
    {"cbsa_code": "37620", "cbsa_name": "Parkersburg-Vienna, WV",                             "metro_type": "metropolitan", "state_abbr": "WV",        "population_rank": 297},
    {"cbsa_code": "19060", "cbsa_name": "Cumberland, MD-WV",                                  "metro_type": "metropolitan", "state_abbr": "MD-WV",     "population_rank": 298},
    {"cbsa_code": "24020", "cbsa_name": "Glens Falls, NY",                                    "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 299},
    {"cbsa_code": "28100", "cbsa_name": "Kankakee, IL",                                       "metro_type": "metropolitan", "state_abbr": "IL",        "population_rank": 300},

    # ── Selected micropolitans and smaller metros (301–400) ──────────────────
    {"cbsa_code": "15500", "cbsa_name": "Burlington, NC",                                     "metro_type": "micropolitan",  "state_abbr": "NC",        "population_rank": 301},
    {"cbsa_code": "24260", "cbsa_name": "Grand Island, NE",                                   "metro_type": "micropolitan",  "state_abbr": "NE",        "population_rank": 302},
    {"cbsa_code": "14100", "cbsa_name": "Bloomsburg-Berwick, PA",                             "metro_type": "micropolitan",  "state_abbr": "PA",        "population_rank": 303},
    {"cbsa_code": "40660", "cbsa_name": "Rome, GA",                                           "metro_type": "micropolitan",  "state_abbr": "GA",        "population_rank": 304},
    {"cbsa_code": "27100", "cbsa_name": "Jackson, MI",                                        "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 305},
    {"cbsa_code": "46900", "cbsa_name": "Walla Walla, WA",                                    "metro_type": "micropolitan",  "state_abbr": "WA",        "population_rank": 306},
    {"cbsa_code": "23580", "cbsa_name": "Gainesville, GA",                                    "metro_type": "metropolitan", "state_abbr": "GA",        "population_rank": 307},
    {"cbsa_code": "11020", "cbsa_name": "Altoona, PA",                                        "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 308},
    {"cbsa_code": "19420", "cbsa_name": "Decatur, IL",                                        "metro_type": "metropolitan", "state_abbr": "IL",        "population_rank": 309},
    {"cbsa_code": "12980", "cbsa_name": "Battle Creek, MI",                                   "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 310},
    {"cbsa_code": "27180", "cbsa_name": "Jackson, TN",                                        "metro_type": "metropolitan", "state_abbr": "TN",        "population_rank": 311},
    {"cbsa_code": "13020", "cbsa_name": "Bay City, MI",                                       "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 312},
    {"cbsa_code": "21300", "cbsa_name": "Elmira, NY",                                         "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 313},
    {"cbsa_code": "20460", "cbsa_name": "Duluth, MN-WI",                                      "metro_type": "metropolitan", "state_abbr": "MN-WI",     "population_rank": 314},
    {"cbsa_code": "38620", "cbsa_name": "Portsmouth, NH-ME",                                  "metro_type": "metropolitan", "state_abbr": "NH-ME",     "population_rank": 315},
    {"cbsa_code": "15260", "cbsa_name": "Brunswick, GA",                                      "metro_type": "micropolitan",  "state_abbr": "GA",        "population_rank": 316},
    {"cbsa_code": "27740", "cbsa_name": "Johnstown, PA",                                      "metro_type": "metropolitan", "state_abbr": "PA",        "population_rank": 317},
    {"cbsa_code": "18380", "cbsa_name": "Columbus, IN",                                       "metro_type": "micropolitan",  "state_abbr": "IN",        "population_rank": 318},
    {"cbsa_code": "19380", "cbsa_name": "Decatur, AL",                                        "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 319},
    {"cbsa_code": "33460", "cbsa_name": "Minneapolis-St. Paul-Bloomington, MN-WI",            "metro_type": "metropolitan", "state_abbr": "MN-WI",     "population_rank": 320},
    {"cbsa_code": "34100", "cbsa_name": "Morristown, TN",                                     "metro_type": "micropolitan",  "state_abbr": "TN",        "population_rank": 321},
    {"cbsa_code": "39580", "cbsa_name": "Raleigh-Cary, NC",                                   "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 322},
    {"cbsa_code": "23460", "cbsa_name": "Gadsden, AL",                                        "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 323},
    {"cbsa_code": "26140", "cbsa_name": "Houma-Thibodaux, LA",                                "metro_type": "metropolitan", "state_abbr": "LA",        "population_rank": 324},
    {"cbsa_code": "36980", "cbsa_name": "Owensboro, KY",                                      "metro_type": "metropolitan", "state_abbr": "KY",        "population_rank": 325},
    {"cbsa_code": "38460", "cbsa_name": "Pine Bluff, AR",                                     "metro_type": "metropolitan", "state_abbr": "AR",        "population_rank": 326},
    {"cbsa_code": "12620", "cbsa_name": "Bangor, ME",                                         "metro_type": "metropolitan", "state_abbr": "ME",        "population_rank": 327},
    {"cbsa_code": "33780", "cbsa_name": "Monroe, MI",                                         "metro_type": "metropolitan", "state_abbr": "MI",        "population_rank": 328},
    {"cbsa_code": "20180", "cbsa_name": "Dothan, AL",                                         "metro_type": "metropolitan", "state_abbr": "AL",        "population_rank": 329},
    {"cbsa_code": "16180", "cbsa_name": "Cape Girardeau, MO-IL",                              "metro_type": "metropolitan", "state_abbr": "MO-IL",     "population_rank": 330},
    {"cbsa_code": "42660", "cbsa_name": "Seattle-Tacoma-Bellevue, WA",                        "metro_type": "metropolitan", "state_abbr": "WA",        "population_rank": 331},
    {"cbsa_code": "38060", "cbsa_name": "Phoenix-Mesa-Chandler, AZ",                          "metro_type": "metropolitan", "state_abbr": "AZ",        "population_rank": 332},
    {"cbsa_code": "45700", "cbsa_name": "Texarkana, TX-AR",                                   "metro_type": "metropolitan", "state_abbr": "TX-AR",     "population_rank": 333},
    {"cbsa_code": "12820", "cbsa_name": "Bartholomew County, IN",                             "metro_type": "micropolitan",  "state_abbr": "IN",        "population_rank": 334},
    {"cbsa_code": "28620", "cbsa_name": "Kingston, NY",                                       "metro_type": "metropolitan", "state_abbr": "NY",        "population_rank": 335},
    {"cbsa_code": "29020", "cbsa_name": "Kokomo, IN",                                         "metro_type": "metropolitan", "state_abbr": "IN",        "population_rank": 336},
    {"cbsa_code": "24420", "cbsa_name": "Grants Pass, OR",                                    "metro_type": "micropolitan",  "state_abbr": "OR",        "population_rank": 337},
    {"cbsa_code": "45220", "cbsa_name": "Tallahassee, FL",                                    "metro_type": "metropolitan", "state_abbr": "FL",        "population_rank": 338},
    {"cbsa_code": "33460", "cbsa_name": "Minneapolis-St. Paul-Bloomington, MN-WI",            "metro_type": "metropolitan", "state_abbr": "MN-WI",     "population_rank": 339},
    {"cbsa_code": "11700", "cbsa_name": "Asheville, NC",                                      "metro_type": "metropolitan", "state_abbr": "NC",        "population_rank": 340},
]
# fmt: on


def get_cbsa_list():
    """Return deduplicated CBSA list keyed by cbsa_code."""
    seen = {}
    for item in CBSA_LIST:
        code = item["cbsa_code"]
        if code not in seen:
            seen[code] = item
    return list(seen.values())


# Quick lookup dict: cbsa_code -> record
CBSA_LOOKUP = {r["cbsa_code"]: r for r in get_cbsa_list()}
