"""
Hand-written and upstream column text (SPEC_137) — the highest-precedence
source of the column dictionary.

``source='upstream'`` rows paraphrase the publisher's own field definitions
(the SEC structured-data readmes, EDGAR API docs) and carry the
``upstream_url``; ``source='curated'`` rows document tables Nexdata builds
(PE marts, the entity master). Keys are ``table.column``; a row may also set
``unit``, ``example``, ``pii`` and ``semantic_type`` (use ``None`` to clear a
glossary guess).

Edit here, then run ``python -m app.catalog.dictionary_build``; the drift
test fails until ``columns.generated.json`` is regenerated.
"""

from __future__ import annotations

from typing import Any, Dict

_FORM_D = "https://www.sec.gov/data-research/sec-markets-data/form-d-data-sets"
_13F = "https://www.sec.gov/data-research/sec-markets-data/form-13f-data-sets"
_INSIDER = "https://www.sec.gov/data-research/sec-markets-data/insider-transactions-data-sets"
_EDGAR = "https://www.sec.gov/search-filings/edgar-application-programming-interfaces"
_ADV = ("https://www.sec.gov/data-research/sec-markets-data/"
        "information-about-registered-investment-advisers-exempt-reporting-advisers")
_IAPD = "https://adviserinfo.sec.gov/compilation"

_B = "business_contact"

# table -> (source, upstream_url, {column: description | dict})
_TABLES: Dict[str, tuple] = {
    # ------------------------------------------------------------------ Form D
    "form_d_filings": ("upstream", _FORM_D, {
        "submission_type": "Form type: D (new notice) or D/A (amendment).",
        "entity_type": "Issuer legal form (corporation, limited partnership, LLC ...).",
        "jurisdiction": "Jurisdiction of incorporation or organisation.",
        "year_of_incorporation": "Year the issuer was incorporated or organised.",
        "industry_group": "Industry group ticked on Item 4 (e.g. Pooled Investment Fund, Biotechnology).",
        "revenue_range": "Issuer revenue range from Item 5, or 'Decline to Disclose'.",
        "related_persons": {"description": "Executive officers, directors and promoters (Item 3) as JSON; "
                                           "names and addresses of natural persons.", "pii": _B},
        "federal_exemptions": "Federal exemptions and exclusions claimed (Item 6), e.g. 06b, 06c, 3C.1, 3C.7.",
        "date_of_first_sale": "Date of first sale in the offering (Item 7); NULL when yet to occur.",
        "more_than_one_year": "True when the offering is expected to last more than one year (Item 8).",
        "is_equity": "Offering includes equity securities (Item 9).",
        "is_debt": "Offering includes debt securities (Item 9).",
        "is_option": "Offering includes options, warrants or other rights to acquire securities (Item 9).",
        "is_security_to_be_acquired": "Offering includes securities to be acquired on exercise (Item 9).",
        "is_pooled_investment_fund": "Offering is of pooled investment fund interests (Item 9).",
        "is_business_combination": "Offering is made in connection with a business combination (Item 10).",
        "minimum_investment": {"description": "Minimum investment accepted from an outside investor (Item 11).",
                               "unit": "USD"},
        "total_offering_amount": {"description": "Total offering amount (Item 13); NULL when indefinite.",
                                  "unit": "USD"},
        "total_amount_sold": {"description": "Total amount sold to date (Item 13).", "unit": "USD"},
        "total_remaining": {"description": "Amount remaining to be sold (Item 13).", "unit": "USD"},
        "total_number_already_invested": "Number of investors who have already invested (Item 14).",
        "accredited_investors": "Number of accredited investors who have invested (Item 14).",
        "non_accredited_investors": "Number of non-accredited investors who have invested (Item 14).",
        "sales_compensation": {"description": "Recipients of sales compensation (Item 12) as JSON; "
                                              "may name natural persons.", "pii": _B},
        "issuer_name": "Name of the primary issuer as filed.",
    }),
    "form_d_offerings": ("upstream", _FORM_D, {
        "file_num": "SEC file number of the offering (021-xxxxx).",
        "is_amendment": "True for a D/A amendment.",
        "previous_accession_number": "Accession number of the filing this amendment amends.",
        "industry_group_type": "Industry group (Item 4).",
        "investment_fund_type": "Fund type for pooled investment funds (hedge, private equity, venture ...).",
        "is_40_act": "Issuer is registered or required to register under the Investment Company Act of 1940.",
        "revenue_range": "Issuer revenue range (Item 5), or 'Decline to Disclose'.",
        "aggregate_net_asset_value_range": "Aggregate net asset value range for funds (Item 5).",
        "federal_exemptions_items_list": "Federal exemptions and exclusions claimed (Item 6).",
        "is_business_combination_transaction": "Offering made in connection with a business combination (Item 10).",
        "duration_of_offering_more_than_one_year": "Offering expected to last more than one year (Item 8).",
        "date_of_first_sale": "Date of first sale (Item 7).",
        "yet_to_occur": "True when the first sale has not yet occurred (Item 7).",
        "total_offering_amount": {"description": "Total offering amount (Item 13); NULL when is_indefinite.",
                                  "unit": "USD"},
        "is_indefinite": "True when the total offering amount is indefinite (Item 13).",
        "total_amount_sold": {"description": "Total amount sold to date (Item 13).", "unit": "USD"},
        "total_remaining": {"description": "Amount remaining to be sold (Item 13).", "unit": "USD"},
        "has_non_accredited_investors": "Securities sold or may be sold to non-accredited investors (Item 14).",
        "total_number_already_invested": "Number of investors who have already invested (Item 14).",
        "sales_commission_amount": {"description": "Sales commissions paid (Item 15).", "unit": "USD"},
        "finders_fees_amount": {"description": "Finders' fees paid (Item 15).", "unit": "USD"},
        "gross_proceeds_used_amount": {"description": "Gross proceeds used for payments to executive officers, "
                                                     "directors or promoters (Item 16).", "unit": "USD"},
        "minimum_investment_accepted": {"description": "Minimum investment accepted from an outside investor "
                                                      "(Item 11).", "unit": "USD"},
    }),
    "form_d_issuers": ("upstream", _FORM_D, {
        "issuer_seq": "Position of the issuer on the filing (1 = primary issuer).",
        "is_primary": "True for the primary issuer of the filing.",
        "entity_name": "Issuer name as filed.",
        "state_or_country_description": "Name of the state or country code in state_or_country.",
        "jurisdiction": "Jurisdiction of incorporation or organisation.",
        "entity_type": "Issuer legal form (corporation, limited partnership, LLC ...).",
        "entity_type_other_desc": "Legal form description when entity_type is 'Other'.",
        "year_of_inc_timespan": "Age bucket of the issuer: over five years, within last five years, yet to be formed.",
        "year_of_inc_value": "Year of incorporation when given.",
        "issuer_previous_names": "Previous issuer names listed on the filing.",
        "edgar_previous_names": "Previous names recorded in EDGAR.",
    }),
    "form_d_related_persons": ("upstream", _FORM_D, {
        "related_person_seq": "Position of the related person on the filing.",
        "relationships": "Relationship(s) to the issuer: Executive Officer, Director, Promoter.",
        "relationship_clarification": "Free-text clarification of the relationship.",
        "state_or_country_description": "Name of the state or country code in state_or_country.",
        "city": {"description": "City of the related person's address.", "pii": _B},
        "zip_code": {"description": "ZIP code of the related person's address.", "pii": _B},
    }),
    "form_d_signatures": ("upstream", _FORM_D, {
        "signature_seq": "Position of the signature block on the filing.",
        "issuer_name": "Issuer the signature is given for.",
        "signature_date": "Date of the signature.",
    }),
    # ---------------------------------------------------------------------- 13F
    "sec_13f_filings": ("upstream", _13F, {
        "submission_type": "Form type: 13F-HR, 13F-HR/A, 13F-NT or 13F-NT/A.",
        "period_of_report": "Calendar quarter end the holdings are reported for.",
        "report_calendar_or_quarter": "Report calendar or quarter as stated on the cover page.",
        "is_amendment": "True for an amendment.",
        "amendment_no": "Amendment number.",
        "amendment_type": "Amendment type: RESTATEMENT or NEW HOLDINGS.",
        "conf_denied_expired": "Confidential treatment request denied or expired.",
        "date_denied_expired": "Date confidential treatment was denied or expired.",
        "date_reported": "Date of the originally reported information that this filing updates.",
        "reason_for_non_confidentiality": "Reason given for making previously confidential holdings public.",
        "filing_manager_name": {"description": "Name of the institutional investment manager filing the report.",
                                "pii": "none"},
        "filing_manager_city": "City of the filing manager's business address.",
        "report_type": "13F HOLDINGS REPORT, 13F NOTICE or 13F COMBINATION REPORT.",
        "form13f_file_number": "The manager's Form 13F file number (028-xxxxx).",
        "sec_file_number": "SEC file number of the manager (e.g. 801- for advisers).",
        "provide_info_for_instruction5": "Manager provides information under Instruction 5 (other managers).",
        "additional_information": "Additional information given on the cover page.",
        "other_included_managers_count": "Number of other included managers.",
        "table_entry_total": "Number of rows in the information table.",
        "is_confidential_omitted": "True when confidential information has been omitted and filed separately.",
        "signature_city": {"description": "City where the signer signed the report.", "pii": _B},
        "signature_state_or_country": {"description": "State or country where the signer signed the report.",
                                       "pii": _B},
        "signature_date": "Date the report was signed.",
        "value_multiplier": "Factor applied to reported values: 1000 for filings before 2023-01-03 "
                            "(reported in thousands), else 1.",
    }),
    "sec_13f_holdings": ("upstream", _13F, {
        "infotable_sk": "Row key of the information-table entry within the filing.",
        "name_of_issuer": "Name of the issuer of the security.",
        "title_of_class": "Title of the class of security.",
        "ssh_prnamt": "Number of shares or principal amount held.",
        "ssh_prnamt_type": "SH (shares) or PRN (principal amount).",
        "put_call": "PUT or CALL when the row reports an option; NULL otherwise.",
        "investment_discretion": "Investment discretion: SOLE, DFND (shared-defined) or OTR (shared-other).",
        "other_manager": "Sequence numbers of other included managers sharing discretion.",
        "voting_auth_sole": "Shares over which the manager has sole voting authority.",
        "voting_auth_shared": "Shares over which the manager has shared voting authority.",
        "voting_auth_none": "Shares over which the manager has no voting authority.",
        "value": {"description": "Market value of the holding in US dollars (pre-2023-01-03 filings reported "
                                 "thousands and are multiplied by 1000).", "unit": "USD"},
    }),
    "sec_13f_other_managers": ("upstream", _13F, {
        "list_type": "Which list the manager appears on: other managers reporting for this manager, or "
                     "other included managers.",
        "sequence_number": "Sequence number of the other manager on the filing.",
        "form13f_file_number": "The other manager's Form 13F file number.",
        "sec_file_number": "The other manager's SEC file number.",
        "name": "Name of the other manager.",
    }),
    # ------------------------------------------------------------------ insider
    "sec_insider_filings": ("upstream", _INSIDER, {
        "period_of_report": "Date of the earliest transaction or event reported.",
        "date_of_orig_sub": "Date of the original submission, for an amendment.",
        "document_type": "Form type: 3, 4, 5 or an amendment (3/A, 4/A, 5/A).",
        "issuer_name": "Name of the issuer whose securities are reported.",
        "no_securities_owned": "Form 3: the reporting person owns no securities of the issuer.",
        "not_subject_sec16": "Reporting person is no longer subject to Section 16.",
        "form3_holdings_reported": "Form 5: Form 3 holdings reported on this form.",
        "form4_trans_reported": "Form 5: Form 4 transactions reported on this form.",
        "aff10b5one": "A transaction was made under a Rule 10b5-1(c) trading plan.",
        "remarks": "Remarks section of the form.",
    }),
    "sec_insider_owners": ("upstream", _INSIDER, {
        "rptowner_name": {"description": "Name of the reporting owner (often a natural person: director, "
                                         "officer or 10% owner).", "pii": _B},
        "relationship": "Relationship(s) of the reporting owner to the issuer.",
        "is_director": "Reporting owner is a director.",
        "is_officer": "Reporting owner is an officer.",
        "is_ten_percent_owner": "Reporting owner holds 10% or more.",
        "is_other": "Reporting owner has another relationship (see other_text).",
        "officer_title": "Officer title when is_officer.",
        "other_text": "Description of the other relationship.",
        "rptowner_city": {"description": "City of the reporting owner's address.", "pii": _B},
        "rptowner_zipcode": {"description": "ZIP code of the reporting owner's address.", "pii": _B},
        "rptowner_state_desc": "Name of the reporting owner's state or country.",
        "file_number": "SEC file number of the reporting owner.",
    }),
    "sec_insider_transactions": ("upstream", _INSIDER, {
        "table_type": "Source table: non-derivative or derivative, transaction or holding.",
        "trans_sk": "Row key of the transaction or holding within the filing.",
        "security_title": "Title of the security.",
        "trans_date": "Transaction date.",
        "deemed_execution_date": "Deemed execution date, when reported.",
        "trans_form_type": "Form type the transaction was reported on.",
        "trans_code": "Transaction code (P purchase, S sale, A grant, M exercise, F tax withholding, G gift ...).",
        "equity_swap_involved": "The transaction involved an equity swap.",
        "trans_timeliness": "E early or L late, when the transaction is reported out of time.",
        "trans_shares": "Number of shares (or units) transacted.",
        "trans_pricepershare": {"description": "Price per share of the transaction.", "unit": "USD"},
        "trans_total_value": {"description": "Total value of the transaction, when reported.", "unit": "USD"},
        "trans_acquired_disp_cd": "A acquired or D disposed.",
        "shrs_ownd_folwng_trans": "Shares owned following the reported transaction(s).",
        "valu_ownd_folwng_trans": {"description": "Value owned following the reported transaction(s).",
                                   "unit": "USD"},
        "direct_indirect_ownership": "D direct or I indirect ownership.",
        "nature_of_ownership": "Nature of indirect beneficial ownership.",
        "conv_exercise_price": {"description": "Conversion or exercise price of the derivative security.",
                                "unit": "USD"},
        "exercise_date": "Date the derivative security becomes exercisable.",
        "expiration_date": "Expiration date of the derivative security.",
        "undlyng_sec_title": "Title of the underlying security.",
        "undlyng_sec_shares": "Number of underlying shares.",
        "undlyng_sec_value": {"description": "Value of the underlying security.", "unit": "USD"},
        "footnote_refs": "Footnote ids attached to the row's fields (JSON).",
    }),
    "sec_insider_footnotes": ("upstream", _INSIDER, {
        "footnote_id": "Footnote id (F1, F2 ...) referenced from the transaction rows.",
        "footnote_txt": "Footnote text.",
    }),
    # -------------------------------------------------------- EDGAR submissions
    "sec_filers": ("upstream", _EDGAR, {
        "name": "Current EDGAR conformed name of the filer.",
        "entity_type": "EDGAR entity type (operating, other, individual ...).",
        "sic_description": "Description of the SIC code.",
        "owner_org": "SEC Division of Corporation Finance office that reviews the filer.",
        "category": "Filer category (large accelerated filer, non-accelerated filer ...).",
        "ein_raw": "EIN exactly as EDGAR holds it (ein is the cleaned 9-digit form).",
        "state_of_incorporation": "State or country of incorporation code.",
        "fiscal_year_end": "Fiscal year end as MMDD.",
        "tickers": "Ticker symbols listed for the filer.",
        "exchanges": "Exchanges matching tickers, in the same order.",
        "investor_website": "Investor-relations website.",
        "biz_state2": "Two-letter US state of the business address (NULL for foreign).",
        "biz_is_foreign": "Business address is outside the US.",
        "mail_state2": "Two-letter US state of the mailing address.",
        "insider_transaction_for_owner_exists": "EDGAR flag: the filer has insider transactions as an owner.",
        "insider_transaction_for_issuer_exists": "EDGAR flag: the filer has insider transactions as an issuer.",
        "flags": "EDGAR flags on the filer record.",
        "former_name_count": "Number of former names (see sec_filer_former_names).",
        "recent_filing_count": "Number of filings in the EDGAR 'recent' block.",
        "latest_filing_date": "Date of the most recent filing.",
        "earliest_recent_filing_date": "Earliest filing date in the EDGAR 'recent' block.",
        "latest_form": "Form type of the most recent filing.",
        "phone": {"description": "Business telephone as published by EDGAR.", "pii": _B},
        "phone10": {"description": "Business telephone normalised to 10 digits.", "pii": _B},
    }),
    "sec_filer_former_names": ("upstream", _EDGAR, {
        "name": "A former conformed name of the filer.",
        "from_date": "Date the former name took effect.",
        "to_date": "Date the former name stopped being used.",
    }),
    "sec_8k_index": ("upstream", _EDGAR, {
        "form": "Form type (8-K, 8-K/A).",
        "report_date": "Date of the earliest event reported.",
        "items": "8-K item numbers reported (e.g. 2.02,9.01).",
        "primary_document": "File name of the primary document.",
        "primary_doc_description": "Description of the primary document.",
        "size": {"description": "Size of the filing.", "unit": "bytes"},
        "file_number": "SEC file number.",
        "film_number": "EDGAR film number.",
    }),
    # ---------------------------------------------------------------------- ADV
    "sec_adv_roster_snapshots": ("upstream", _ADV, {
        "roster_date": "Date of the SEC monthly adviser roster this row comes from.",
        "adviser_type": "RIA (registered investment adviser) or ERA (exempt reporting adviser).",
        "sec_region": "SEC regional office responsible for the adviser.",
        "sec_number": "SEC file number (801- registered, 802- exempt).",
        "firm_type": "Organisation type (corporation, LLC, partnership ...).",
        "legal_name": "Adviser's legal name.",
        "business_name": "Primary business name.",
        "sec_status": "SEC registration status on the roster date.",
        "form_version": "Form ADV version of the latest filing.",
        "sec_status_effective_date": "Date the SEC status took effect.",
        "latest_filing_date": "Date of the adviser's latest Form ADV filing.",
        "notice_filed_states": "States where the adviser made notice filings.",
        "other_office_count": "Number of offices other than the principal office.",
        "employees_total": "Total employees (Item 5.A).",
        "employees_investment_advisory": "Employees performing investment advisory functions (Item 5.B(1)).",
        "clients_individuals": "Individual (non-high-net-worth) clients (Item 5.D).",
        "clients_hnw": "High-net-worth individual clients (Item 5.D).",
        "clients_pooled_vehicles": "Pooled investment vehicle clients (Item 5.D).",
        "clients_count": "Approximate total number of clients (Item 5.C).",
        "accounts_discretionary": "Number of discretionary accounts (Item 5.F).",
        "accounts_non_discretionary": "Number of non-discretionary accounts (Item 5.F).",
        "accounts_total": "Total number of accounts (Item 5.F).",
        "private_fund_count": "Number of private funds advised (Schedule D 7.B).",
        "aum_discretionary": {"description": "Discretionary regulatory assets under management (Item 5.F).",
                              "unit": "USD"},
        "aum_non_discretionary": {"description": "Non-discretionary regulatory AUM (Item 5.F).", "unit": "USD"},
        "aum_total": {"description": "Total regulatory assets under management (Item 5.F).", "unit": "USD"},
        "custody_amount": {"description": "Client assets held in custody (Item 9).", "unit": "USD"},
        "private_fund_gross_assets": {"description": "Gross asset value of private funds advised.", "unit": "USD"},
        "custody_client_cash_securities": "Adviser has custody of client cash or securities (Item 9.A).",
        "custody_related_person": "A related person has custody of client assets (Item 9.B).",
        "has_disciplinary_disclosure": "Any disciplinary disclosure answered yes (Item 11).",
        "drp_flags": "Disciplinary disclosure (DRP) answers by item, as JSON.",
        "drp_disclosure_total": "Number of disciplinary disclosure questions answered yes.",
    }),
    "sec_adv_feed_firm_state": ("upstream", _IAPD, {
        "edition_date": "Date of the IAPD compilation feed edition.",
        "sec_region": "SEC regional office responsible for the adviser.",
        "sec_number": "SEC file number (801- registered, 802- exempt).",
        "firm_type": "Organisation type.",
        "registration_status": "Registration status in the feed edition.",
        "registration_date": "Date of registration.",
        "form_version": "Form ADV version of the latest filing.",
        "employees_total": "Total employees.",
        "aum_discretionary": {"description": "Discretionary regulatory AUM.", "unit": "USD"},
        "aum_non_discretionary": {"description": "Non-discretionary regulatory AUM.", "unit": "USD"},
        "aum_total": {"description": "Total regulatory assets under management.", "unit": "USD"},
        "accounts_total": "Total number of accounts.",
        "notice_filed_states": "States where the adviser made notice filings.",
    }),
    "sec_form_adv": ("curated", _ADV, {
        "sec_number": "SEC file number (801- registered, 802- exempt).",
        "doing_business_as": "Name the firm does business under.",
        "registration_status": "Registration status.",
        "registration_date": "Date of registration.",
        "state_registrations": "States where the firm is registered.",
        "assets_under_management": {"description": "Regulatory assets under management.", "unit": "USD"},
        "aum_date": "Date the AUM figure refers to.",
        "aum_currency": "Currency of assets_under_management.",
        "total_client_count": "Total number of clients.",
        "individual_client_count": "Individual (non-high-net-worth) clients.",
        "high_net_worth_client_count": "High-net-worth individual clients.",
        "pooled_investment_vehicle_count": "Pooled investment vehicle clients.",
        "is_family_office": "Firm identified as a family office.",
        "is_registered_with_sec": "Registered with the SEC.",
        "is_registered_with_state": "Registered with a state regulator.",
        "key_personnel": {"description": "Key personnel (names, titles) as JSON.", "pii": _B},
        "form_adv_url": "Link to the Form ADV on IAPD.",
        "last_amended_date": "Date of the latest amendment.",
    }),
    "sec_adv_filings": ("upstream", _ADV, {
        "filing_id": "Form ADV filing id in the SEC data set.",
        "adviser_type": "RIA or ERA.",
        "sec_number": "SEC file number.",
        "form_version": "Form ADV version.",
        "filed_at": "Date and time the filing was submitted.",
    }),
    "sec_adv_private_fund_filings": ("upstream", _ADV, {
        "filing_id": "Form ADV filing id the Schedule D section belongs to.",
        "private_fund_id": "SEC private fund identification number (805-xxxxxxxxxx).",
        "adviser_type": "RIA or ERA.",
        "fund_name": "Name of the private fund.",
        "fund_name_core": "Fund name normalised for matching (legal suffixes and punctuation removed).",
        "reference_id": "Filer's reference id for the fund section.",
        "org_state": "State of organisation of the fund.",
        "org_country": "Country of organisation of the fund.",
        "excl_3c1": "Relies on the Investment Company Act 3(c)(1) exclusion.",
        "excl_3c7": "Relies on the Investment Company Act 3(c)(7) exclusion.",
        "is_master_fund": "The fund is a master fund in a master-feeder arrangement.",
        "is_feeder_fund": "The fund is a feeder fund in a master-feeder arrangement.",
        "master_fund_name": "Name of the master fund, for a feeder.",
        "master_fund_id": "Private fund id of the master fund, for a feeder.",
        "is_fund_of_funds": "The fund is a fund of funds.",
        "invests_in_self_or_related": "Fund of funds invests in funds advised by the adviser or a related person.",
        "invests_in_securities": "The fund invests in securities of registered investment companies.",
        "fund_type": "Fund type: hedge, liquidity, private equity, real estate, securitized asset, "
                     "venture capital or other.",
        "fund_type_other": "Fund type description when fund_type is other.",
        "gross_asset_value": {"description": "Current gross asset value of the fund.", "unit": "USD"},
        "minimum_investment": {"description": "Minimum investment commitment required of an investor.",
                               "unit": "USD"},
        "owners": "Approximate number of beneficial owners.",
        "pct_owned_you_or_related": {"description": "Percentage owned by the adviser and related persons.",
                                     "unit": "percent"},
        "pct_owned_funds": {"description": "Percentage owned by funds of funds.", "unit": "percent"},
        "sales_limited": "Sales limited to qualified clients.",
        "pct_owned_non_us": {"description": "Percentage owned by non-US persons.", "unit": "percent"},
        "has_subadviser": "The fund has a sub-adviser.",
        "other_ias_advise": "Other investment advisers advise the fund.",
        "clients_solicited": "Adviser's clients are solicited to invest in the fund.",
        "pct_invested": {"description": "Percentage of the adviser's clients invested in the fund.",
                         "unit": "percent"},
        "exempt_from_registration": "Fund relies on an exemption from registration of its securities.",
        "annual_audit": "Financial statements are subject to an annual audit.",
        "gaap": "Audited financial statements are prepared under US GAAP.",
        "fs_distributed": "Audited financial statements are distributed to investors.",
        "unqualified_opinion": "Whether the auditor's opinion was unqualified (Y / N / report not yet received).",
        "prime_brokers": "The fund uses one or more prime brokers.",
        "custodians": "The fund uses one or more custodians.",
        "administrator": "The fund uses an administrator.",
        "pct_assets_valued": {"description": "Percentage of assets valued by a person other than the adviser.",
                              "unit": "percent"},
        "marketing": "The fund uses marketers (placement agents, solicitors).",
    }),
    # ------------------------------------------------------------- PE marts
    "sec_adv_private_funds": ("curated", _ADV, {
        "crd_number": "CRD of the adviser whose latest Schedule D lists the fund.",
        "private_fund_id": "SEC private fund identification number (805-xxxxxxxxxx).",
        "filing_id": "Form ADV filing the current state was taken from.",
        "adviser_type": "RIA or ERA.",
        "as_of_date": "Filing date of the Schedule D the current state comes from.",
        "fund_name_core": "Fund name normalised for matching.",
        "fund_type": "Fund type as filed (hedge, private equity, venture capital ...).",
        "fund_type_other": "Fund type description when fund_type is other.",
        "gross_asset_value": {"description": "Gross asset value from the latest filing.", "unit": "USD"},
        "is_master_fund": "Master fund in a master-feeder arrangement.",
        "is_feeder_fund": "Feeder fund in a master-feeder arrangement.",
        "master_fund_id": "Private fund id of the master fund, for a feeder.",
        "master_fund_name": "Name of the master fund, for a feeder.",
        "org_state": "State of organisation.",
        "org_country": "Country of organisation.",
        "excl_3c1": "Relies on the 3(c)(1) exclusion.",
        "excl_3c7": "Relies on the 3(c)(7) exclusion.",
    }),
    "pe_firms": ("curated", None, {
        "employee_count": "Number of employees, when known.",
        "founded_year": "Year the firm was founded, when known.",
        "is_sec_registered": "Firm is registered with the SEC as an investment adviser.",
        "is_spv_platform": "Files many vehicles but raises no fund of its own: an SPV / access platform "
                           "rather than a sponsor (set by the pe_people mart).",
        "last_verified_date": "Date the row was last verified.",
    }),
    "pe_funds": ("curated", None, {
        "firm_id": "pe_firms.id of the manager; NULL when no manager could be attributed.",
        "vintage_year": "Vintage year of the fund.",
        "target_size_usd_millions": {"description": "Target fund size.", "unit": "USD millions"},
        "final_close_usd_millions": {"description": "Final close size.", "unit": "USD millions"},
        "first_close_date": "Date of first close.",
        "final_close_date": "Date of final close.",
        "fund_life_years": "Fund term in years.",
        "investment_period_years": "Investment period in years.",
        "sec_file_number": "SEC file number linked to the fund.",
    }),
    "pe_people": ("curated", None, {
        "current_title": "Current title.",
        "current_company": "Current employer.",
        "bio": {"description": "Biography text.", "pii": _B},
        "personal_website": {"description": "Personal website.", "pii": "personal"},
        "source_key": "Identity key for SEC-derived rows (NULL on hand-collected rows).",
        "is_active": "Person is active in the PE ecosystem.",
        "data_sources": "Sources the row was built from (JSON).",
        "last_verified": "Date the row was last verified.",
    }),
    "pe_firm_people": ("curated", None, {
        "firm_id": "pe_firms.id.",
        "person_id": "pe_people.id.",
        "role_type": "Role family: investment_team, operating_partner, advisory_board, lpac_member, "
                     "ir_fundraising, finance_ops.",
        "sector_focus": "Sector focus of the person at the firm (JSON).",
        "geography_focus": "Geography focus of the person at the firm (JSON).",
        "start_date": "Start of the role.",
        "end_date": "End of the role.",
        "is_current": "Role is current.",
        "person_link_method": "How the person was linked (e.g. Form D related person, ADV schedule A).",
        "firm_link_method": "Fund attribution tier propagated from pe_funds.firm_link_method.",
        "address_confirmation": "Whether the person's filing address matched the firm's.",
        "fund_count": "Number of the firm's funds the person appears on.",
        "filing_count": "Number of filings the person appears on for the firm.",
        "first_seen": "First filing date linking the person to the firm.",
        "last_seen": "Last filing date linking the person to the firm.",
    }),
    # ---------------------------------------------------------- entity master
    "core.source_record": ("curated", None, {
        "record_key": "Stable key of the source record: <source>:<native id>.",
        "native_id": "Id of the record in its source system.",
        "name_norm": "Legal name normalised for matching.",
        "name_norm_version": "Version of the name normaliser that produced name_norm.",
        "state_entity_id": "State business-registry entity id, when known.",
        "observed_at": "When the source last reported this record.",
        "domain": "Web domain of the organisation.",
    }),
    "core.entity": ("curated", None, {
        "entity_id": "Nexdata entity id (stable across resolver runs unless merged; see superseded_by).",
        "entity_type": "Entity kind; 'org' today.",
        "canonical_name": "Best legal name across member records.",
        "state_entity_id": "State business-registry entity id.",
        "canonical_state": "Best US state across member records.",
        "canonical_zip5": "Best ZIP5 across member records.",
        "canonical_domain": "Best web domain across member records.",
        "member_count": "Number of source records resolved into the entity.",
        "strong_key_count": "Number of strong identifiers (EIN/CIK/CRD/LEI/UEI) the entity carries.",
        "match_tier": "Strongest match tier that joined the members.",
        "field_conflicts": "Member records that disagree on a canonical field (JSON).",
        "last_members": "Most recent member record keys (JSON).",
        "resolver_version": "Resolver version that last wrote the entity.",
        "dissolved_at": "When the entity was dissolved by a merge.",
        "superseded_by": "entity_id that absorbed this one after a merge.",
    }),
    "core.membership": ("curated", None, {
        "record_key": "core.source_record key.",
        "entity_id": "core.entity id the record resolved into.",
        "match_tier": "Tier of the rule that matched the record.",
        "match_method": "Rule that matched the record (e.g. shared CIK).",
        "features": "Match evidence (JSON).",
    }),
    "core.identifier": ("curated", None, {
        "id_type": "Identifier type: ein, cik, crd, lei, uei ...",
        "id_value": {"description": "Identifier value. CIKs are stored unpadded: join to SEC tables with "
                                    "lpad(ltrim(id_value,'0'),10,'0') (the cik normalize_sql).",
                     "example": "25743"},
        "entity_id": "core.entity id the identifier belongs to.",
        "sources": "Sources that reported the identifier.",
        "first_seen": "First time the identifier was seen.",
        "last_seen": "Last time the identifier was seen.",
    }),
    "core.alias": ("curated", None, {
        "entity_id": "core.entity id.",
        "name_norm": "Normalised name.",
    }),
    "core.key_veto": ("curated", None, {
        "key_type": "Identifier type the veto applies to.",
        "key_value": "Identifier value that must not be used for matching.",
        "record_key": "Record the veto is limited to ('*' = all records).",
        "reason": "Why the key was vetoed.",
        "actor": "Who recorded the veto.",
        "revoked_at": "When the veto was revoked.",
    }),
    "core.entity_merge": ("curated", None, {
        "absorbed_entity_id": "Entity that was dissolved.",
        "survivor_entity_id": "Entity that absorbed it.",
        "cause": "Evidence for the merge (JSON).",
        "merged_at": "When the merge happened.",
    }),
    "core.resolve_run": ("curated", None, {
        "run_at": "Start time of the resolver run.",
        "resolver_version": "Resolver version.",
        "dry_run": "Run computed results without writing them.",
        "duration_seconds": {"description": "Run duration.", "unit": "seconds"},
        "metrics": "Run metrics (JSON).",
    }),
    "core.cik_crd_bridge": ("curated", None, {
        "tier": "Winning evidence tier: cover_page_crd, other_manager_crd or name_state.",
        "tier_rank": "Rank of the tier (1 strongest).",
        "matched_on": "What the tier matched on.",
        "evidence": "Evidence rows for the match (JSON).",
        "crd_cik_count": "How many CIKs claim the same CRD (the relation is many-to-many; a warning, not a key).",
        "builder_version": "Bridge builder version.",
        "built_at": "When the bridge row was built.",
    }),
    "core.cik_crd_bridge_refused": ("curated", None, {
        "reason": "Why no CRD was accepted for the CIK (conflicting tiers, several candidates ...).",
        "tier": "Tier that produced the conflicting candidates.",
        "candidates": "Candidate CRDs with their evidence (JSON).",
        "built_at": "When the refusal was recorded.",
    }),
    # ------------------------------------------- natural-person names the name rules miss
    "oc_officers": ("curated", None, {
        "name": {"description": "Officer or director name as published by OpenCorporates; usually a natural "
                                "person.", "pii": _B},
    }),
    "family_offices": ("curated", None, {
        "principal_name": {"description": "Main family member behind the office (a natural person).", "pii": _B},
        "principal_family": {"description": "Family behind the office (a family surname).", "pii": _B},
    }),
    # ---------------------------------------------------------------- people
    "people": ("curated", None, {
        "email": {"description": "Email address. Most values are inferred (guessed from a pattern), not "
                                 "published; see email_confidence. Never exported.", "pii": "personal"},
        "email_confidence": "How the email was obtained: verified, inferred or guessed.",
    }),
}


def _flatten() -> Dict[str, Dict[str, Any]]:
    out: Dict[str, Dict[str, Any]] = {}
    for table, (source, url, cols) in _TABLES.items():
        for col, val in cols.items():
            row = dict(val) if isinstance(val, dict) else {"description": val}
            row.setdefault("source", source)
            if url and row["source"] == "upstream":
                row.setdefault("upstream_url", url)
            out[f"{table}.{col}"] = row
    return out


CURATED: Dict[str, Dict[str, Any]] = _flatten()
